oasisprotocol/nexus

Makefile

Fix doc building command

---

api/v1/client.go
api/v1/types.go

Present empty arrays

---

api/spec/v1.yaml
api/v1/client.go
api/v1/types.go
tests/http/v1/staking_test.go

Remove total field from Account

---

analyzer/consensus/consensus.go
api/spec/v1.yaml

**Why**
I missed a spot from #103

Fix amount usage in Account escrow balance debonding

---

analyzer/consensus/consensus.go
analyzer/consensus/queries.go
storage/oasis/client.go

Fix removal of debonding delegations

---

storage/generator/generator.go
storage/migrations/0007_oasis_3_add_reserved_addresses.up.sql

**Why**
Close #93. See CU-3r2m0w5.

Add reserved addresses

---

config/docker-dev.yml

Fix Docker dev configuration

---

analyzer/consensus/consensus.go

**Why**
I was erroneously updating a non-existing epoch.

Fix epoch bug

---

Makefile
README.md
analyzer/consensus/consensus.go
analyzer/emerald/emerald.go
cmd/analyzer/analyzer.go
config/local-dev.yml
storage/postgres/client.go

Various small improvements to readability, logging, local testing, and variable naming.
Titles of individual commits explain changes in slightly more detail.

Assorted small fixes

---

.github/CODEOWNERS

**Why**
Let's go! 🚀
Also, selfishly unblock #155

Add mitjat to code owners

---

storage/migrations/0000_oasis_3_init.up.sql
storage/migrations/0009_oasis_3_emerald_init.up.sql
tests/e2e/migrations/0000_oasis_3_test_e2e.up.sql

db: Remove extra_data fields

---

analyzer/api.go
analyzer/emerald/emerald.go
analyzer/emerald/incoming.go
analyzer/queries.go
config/config.go
storage/migrations/0009_oasis_3_emerald_init.up.sql

- awkward runtime id https://github.com/oasisprotocol/oasis-indexer/pull/141#discussion_r990572194
- awkward chain context https://github.com/oasisprotocol/oasis-indexer/pull/141#discussion_r990572448

Emerald: unhardcode runtime ID and chain context

---

analyzer/emerald/incoming.go
storage/migrations/0009_oasis_3_emerald_init.up.sql

Emerald: store some fields as bytea

---

analyzer/emerald/incoming.go

for #166 
also a missing error wrap

Emerald: rename loop var in long loop

---

analyzer/uncategorized/evm_raw_tx_test.go

Emerald: put test data in structs

---

.github/workflows/docker-indexer.yaml

Improve consistency with other repos.

Add Docker workflow comment

---

analyzer/emerald/emerald.go
analyzer/emerald/incoming.go
analyzer/queries.go

Emerald: add new inserts to QueryFactory

---

api/common/errors.go
api/spec/v1.yaml
api/v1/client.go
api/v1/handlers.go
api/v1/middleware.go
api/v1/v1.go
storage/client/api.go
storage/client/client.go
storage/client/queries.go
storage/client/types.go
storage/migrations/02_oasis_3_emerald.up.sql

I'm working on this approach, which I hope we can use re-use it for multiple runtimes

Emerald: list blocks api

---

analyzer/consensus/genesis.go
config/local-dev.yml

Follow-up to a @pro-wh comment in #176 
Also adds a comment+formatting to the config doc (both no-op)

nit: Rename poorly named func

---

analyzer/emerald/incoming.go
api/spec/v1.yaml
api/v1/client.go
api/v1/handlers.go
api/v1/logic.go
api/v1/types.go
api/v1/v1.go
storage/client/api.go
storage/client/client.go
storage/client/queries.go
storage/client/types.go

I'll be importing some more from nexus to fill in the tx decoding
https://github.com/oasisprotocol/oasis-nexus/pull/1/files#diff-e1035a745a4c1961a3b1d548117d5fad7dc41575180884255a93486ca18bdd5dR91

Emerald: list transactions api

---

api/v1/client.go
api/v1/handlers.go
api/v1/v1.go
storage/client/api.go
storage/client/client.go
storage/client/queries.go
storage/client/types.go

here's an endpoint to do an index scan for most-number-of-holders tokens
all we have right now is the token contract address (oasis address) and that number of holders

Emerald: add tokens api

---

analyzer/emerald/emerald.go
analyzer/emerald/incoming.go
analyzer/evmabi/README.md
analyzer/evmabi/contracts/ERC20.sol
analyzer/evmabi/contracts/artifacts/ERC20.json
analyzer/evmabi/evmabi.go
analyzer/modules/evm.go
analyzer/modules/evm_test.go
analyzer/queries.go
storage/api.go
storage/migrations/02_oasis_3_emerald.up.sql
storage/oasis/runtime.go

we have a runtime client. let's run evm calls to query the ERC-20 `name` etc

Emerald: query token name etc

---

api/v1/client.go
storage/client/api.go
storage/client/client.go
storage/client/types.go
tests/e2e/e2e_test.go
tests/http/v1/governance_test.go
tests/http/v1/staking_test.go
tests/http/v1/transactions_test.go

api: Show large numbers as strings

---

Makefile
analyzer/consensus/consensus.go
analyzer/util/util.go
config/docker-dev.yml
storage/api.go
storage/oasis/consensus.go

analyzer: Index all services backends' events

---

analyzer/modules/evm.go

this helps us filter out other contracts that happen to have a matching Transfer log topic
incidentally, our storage glue code can't handle nil big ints -> db numerics, and this avoids that as well

evm: require ERC-20 totalSupply

---

analyzer/emerald/incoming.go
analyzer/modules/evm.go
analyzer/uncategorized/eth.go
analyzer/uncategorized/visitors.go
api/v1/logic.go
storage/api.go
storage/oasis/runtime.go

Emerald: fix legacy EVM and ERC capitalization

---

api/v1/handlers.go

fixes #196 
actually some of these had incorrectly logged a serialization error as a database error :eyes:

api: extract replyJSON method

---

storage/client/queries.go

If a validator's stake (ie stake delegated to it) drops to zero, trying to fetch the account info of any account that ever delegated stake to that validator will trigger a divide by 0 error.
Example: 
https://index.oasislabs.com/v1/consensus/accounts/oasis1qr8znzva3h28hausy7n3fput0fn80sajeywmwp5y

[api] check for divide-by-zero

---

api/spec/v1.yaml
api/v1/strict_server.go
storage/client/client.go
storage/client/queries.go

Implement `/emerald/transactions/{tx_hash}`

---

api/spec/v1.yaml
api/v1/strict_server.go
api/v1/types/util.go
storage/client/client.go
storage/client/queries.go
storage/migrations/03_agg_stats.up.sql

Resolves #259 
I also restructured the underlying materialized view slightly so that it will be easier to support other paratimes in the future.

Implement /emerald/stats/tx_volume

---

go.mod
go.sum

for sapphire #305. might also help #301, dunno

bump oasis-sdk

---

api/middleware.go

Group all 4xx results under the same "ignored" label, as they're mostly just bots and we're not interested in those requests for metrics anyway.

metrics: Ignore 4xx results

---

analyzer/modules/evm.go
analyzer/uncategorized/addresses.go

cosmetic changes

---

analyzer/evmtokens/evm_tokens.go

EVM: prevent concurrent QueryBatch access 

---

config/docker-dev.yml
config/local-dev.yml

in case people would like to see that they can index sapphire
although, are these in use anywhere? comment if this breaks anything that isn't set up with sapphire

config: add sapphire analyzer to samples

---

config/docker-dev.yml
config/local-dev.yml

ops team requested an explanation of this `from` value. adding it here too

config: add comment about sapphire start round

---

analyzer/consensus/genesis.go

Resolves https://app.clickup.com/t/8669n7exy
Todo:
- The second commit factors out all the multiline strings into consts in queries.go. I'm not sure I want to keep this commit because it makes it much less readable imo. Reviewers please view just the first commit to compare. The multiline strings are also quite messy but imo it's easier to parse on the (hopefully) rare occasions when we'd need to go back and read this file.
- debonding delegations have no primary key and thus the the entire table is superseded by the genesis document debonding delegations list. All other tables will be updated on conflict
- It might be nice to have some sort of warning when conflicts occur for most tables; in theory the genesis document at block N should match the indexer state up to N... though I'm sure …

add upserts to genesis analyzer; some cleanup

---

analyzer/runtime/extract.go

sample run on block 5204809 https://explorer.emerald.oasis.dev/tx/0x0c72020e799e069c6ff2e82a33f5eaaf2919bd6a6eb0cd845bdb62eef723a574/logs

runtime: store unrecognized evm log events

---

api/spec/v1.yaml

Update API endpoint description.

Update API endpoint description

---

CONTRIBUTING.md

Follows https://github.com/oasisprotocol/docs/pull/428

Update discord link

---

analyzer/consensus/consensus.go
storage/oasis/nodeapi/cobalt/node.go
storage/oasis/nodeapi/damask/node.go

as they say, the proposer can propose anything. the committee decides if it's valid, but it's still part of the block

consensus: make malformed transaction not fail

---

.github/CODEOWNERS

Add @ptrus to CODEOWNERS

---

cmd/analyzer/analyzer.go

**Background:**
As discussed in https://app.clickup.com/t/866ahgf2a:
Sometimes, the KVStore does not close cleanly on shutdown. The underlying reason is that k8s force-quits the indexer, and the underlying reason for that is that we don't close the KVStore until all analyzers (which depend on the KVStore) have exited cleanly. But it turns out that that can take more than a minute (which is how long k8s waits).
This means that a routine redeploy can cause hours of downtime: Non-cleanly-closed KVStore can need that long to reindex the several 100GB of cache.
**Change:**
This PR makes it so that on shutdown, we now wait for the analyzers to finish for a _short_ while, then close the KVStore even if not all analyzers finished cleanly.
An underlying issue remains: Analyzers should ideally …

Close IO resources (KVStore!) even if analyzers are slow to shut down

---

CONTRIBUTING.md

Update a small documentation thing.

Update CONTRIBUTING.md branch name reference

---

api/spec/v1.yaml

Update URLs used in generated documentation.

Update API spec base URL

---

analyzer/evmtokens/evm_tokens.go
analyzer/queries/queries.go
analyzer/runtime/evm/client.go
analyzer/runtime/extract.go
analyzer/runtime/runtime.go
storage/migrations/02_runtimes.up.sql

https://app.clickup.com/t/863h6t2mc
todo:
[] testing (preferably find some similar sequence of blocks to what warren used to test 459)

[analyzer] dead reckon erc721 total supply

---

api/spec/v1.yaml

Mark charged_fee as required

---

api/spec/v1.yaml
storage/client/client.go
tests/e2e_regression/expected/emerald_status.body
tests/e2e_regression/expected/status.body
tests/e2e_regression/run.sh

Follow up of https://github.com/oasisprotocol/nexus/pull/496#discussion_r1309539679

[api] change format of latest_update to int64

---

analyzer/queries/queries.go

fix typo in evm_tokens query

---

.github/workflows/ci-lint.yaml
README.md

and people make fun of npm projects for having devDependencies

README: add tools install instructions

---

config/history.go

Based on the upgrade [genesis.json](https://github.com/oasisprotocol/testnet-artifacts/releases/tag/2023-10-12) roothash -> runtime_states
```
"runtime_states": {
"0000000000000000000000000000000000000000000000000000000000000000": {       <-- Cipher
"state_root": "a830eb2a4cde0704ee301673c747e9053a37e1f6315158a71af24cc59821dfb8",
"round": 1730319
},
"000000000000000000000000000000000000000000000000000000000000ff00": {
"state_root": "73ee958c8d3e57f935189125029779e0abed7500a878a3f4b71a4377baf57ddb",
"round": 1
},
"000000000000000000000000000000000000000000000000000000000000ff01": {
"state_root": "28b2af241bc505726fc935ab73ac59cfa4462fec37b91d2cf322c68abc1c2dc2",
"round": 2085
},
"000000000000000000000000000000000000000000000000000000000000ff02": {
"state_root": …
```

add testnet history record for 2023-10-12 upgrade

---

analyzer/consensus/consensus.go
analyzer/queries/queries.go
analyzer/runtime/extract.go
analyzer/runtime/runtime.go
storage/migrations/21_evm_nfts.up.sql
storage/migrations/22_evm_nfts.up.sql

stores an 'owner' field with the destination of the last transfer. it's anticipated that "burns" will transfer to 0x00...00 and leave it there. our record of the nft will still exist

NFT transfer tracking

---

api/spec/v1.yaml
api/v1/strict_server.go
storage/client/client.go
storage/client/queries/queries.go
storage/migrations/21_evm_nfts.up.sql
storage/migrations/22_evm_nfts.up.sql
tests/e2e_regression/expected/emerald_account_nfts.body
tests/e2e_regression/expected/emerald_account_nfts.headers
tests/e2e_regression/expected/emerald_token_nfts.body
tests/e2e_regression/run.sh

> /{runtime}/accounts/{address}/evm_nfts

NFT query by owner

---

api/spec/v1.yaml
api/v1/strict_server.go
storage/client/client.go
storage/client/queries/queries.go
tests/e2e_regression/expected/emerald_token_nft.body
tests/e2e_regression/expected/emerald_token_nft.headers
tests/e2e_regression/run.sh

https://github.com/oasisprotocol/nexus/pull/514#discussion_r1341689174
> for getting data about a specific NFT instance

NFT query by ID

---

api/spec/v1.yaml
api/v1/strict_server.go
tests/e2e_regression/expected/emerald_account_nfts_token.body
tests/e2e_regression/expected/emerald_account_nfts_token.headers
tests/e2e_regression/run.sh

> optional parameter for filtering by token contract address
for https://github.com/oasisprotocol/nexus/pull/529#discussion_r1339572741

api: filter NFTs by owner and token addr

---

analyzer/runtime/evm/erc721.go

previous code was designed to save whatever the server said, mismatched with the db schema which expected JSON. this new routine round-trips the result through Go json decode+encode (+decode :roll_eyes:) so that we only keep valid JSON.

runtime/evm: prevent saving invaild NFT metadata JSON

---

common/types.go
common/types_test.go

common.BigInt.String() and some unprovoked changes

---

analyzer/item/item.go

we had just been throwing these away and only propagating the first :skull:

analyzer: log item errors

---

tests/statecheck/runtime_test.go

Useful for quickly seeing the number of account discrepancies in a statecheck run.

tests/statecheck/runtime: Report the number of balance discrepancies

---

api/spec/v1.yaml
config/docker-dev.yml
config/local-dev.yml
storage/client/client.go
storage/client/queries/queries.go
storage/migrations/06_runtime_events_nft_transfers.up.sql
tests/e2e_regression/expected/emerald_events_by_nft.body
tests/e2e_regression/expected/emerald_events_by_nft.headers
tests/e2e_regression/run.sh

/{runtime}/events:
- contract_address
- nft_id
aaa it's so divisive

api: add NFT-oriented event filtering

---

api/spec/v1.yaml
storage/client/client.go
storage/client/queries/queries.go
tests/e2e_regression/expected/emerald_account_nfts.body
tests/e2e_regression/expected/emerald_account_nfts_token.body
tests/e2e_regression/expected/emerald_token_nft.body
tests/e2e_regression/expected/emerald_token_nfts.body

we had this, here's a field for it

API: add NFT num_transfers

---

storage/client/queries/queries.go

nft_id is a uint256 from ethereum

storage: correct nft id type

---

analyzer/evmabibackfill/evm_abi_backfill.go
analyzer/queries/queries.go

use coalesce for backfill analyzer queries

---

storage/oasis/nodeapi/file/kvstore.go

This PR adds manual management of pogreb backups to work around a problematic situation when
a) the pogreb store needs reindexing and
b) the sapphire or emerald nodes are unavailable.
Because of (b), nexus initialization keeps failing in a fatal way. But by the time that fatal error occurs, pogreb has already started the recovery process, including .bac creation. Then k8s keeps restarting nexus, so the .bac files pile up, until eventually the pogreb recovery fails (because it cannot create backups) and nexus terminates before it even tries to connect to the runtime node. At that point, every restart will fail, so when the runtime node eventually comes back up, nexus never learns about it.
With this PR, nexus cleans up the backups itself using the following cleanup procedure: If a backup …

pogreb: Remove .bac.bac files manually

---

analyzer/evmnfts/multiproto/multiproto.go

Some nft metadata URIs are encoded as `data:...` directly. This PR updates the fetching in `multiproto.go` to parse this accordingly.
Clickup ticket: https://app.clickup.com/t/8693fuwam
Testing: Manually tested on the Testnet nft at https://explorer.dev.oasis.io/testnet/sapphire/token/0xA74A919e0860d398eB258b579f2350c7B8F564a4
```
~/oasis/private-ops(master*) » curl "http://localhost:8008/v1/sapphire/evm_tokens/oasis1qz669dah58ry9c85mvcwtr3ndkp08sxutcw9f4t5/nfts" | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 47953    0 47953    0     0   823k      0 --:--:-- --:--:-- --:--:--  883k
{
"evm_nfts": [
{
"description": "Oasis Consensus 2023 Swag",
"id": "2",
"image": …
```

Handle data uris

---

.changelog/668.internal.md
.github/workflows/ci-lint.yaml
.github/workflows/ci-test.yaml
.github/workflows/docker-nexus.yaml
.github/workflows/prepare-release.yaml
.punch_config.py
.punch_version.py
Makefile
common.mk

Migration of Punch tool. Looking at repos there is an assumption that everyone has `Punch` tool installed locally `pip install punch.py`.

Use Punch tool for tracking and bumping project's version

---

.changelog/666.internal.1.md
.changelog/666.internal.2.md
.changelog/666.internal.3.md
.changelog/666.internal.md
.gitlint
.markdownlint.yml
CONTRIBUTING.md
README.md
common.mk
scripts/add_changelog
scripts/git-hooks/README.md
scripts/git-hooks/pre-commit
scripts/git-hooks/pre-push
scripts/git-hooks/prepare-commit-msg

This PR adds optional git hooks and scripts that make it easier for code contributors to live with `gitlint` and `markdownlint`.

towncrier, gitlint: Workflow automation

---

.changelog/674.process.md
.github/workflows/ci-lint.yaml
CHANGELOG.md
Makefile
analyzer/evmabi/README.md
api/README.md
coreapi/README.md
docker/README.md
storage/migrations/README.md
tests/README.md
tests/load/README.md

Enable markdownlint in CI

---

.changelog/616.feature.md
analyzer/consensus/messages.go
api/spec/v1.yaml
api/v1/strict_server.go
storage/client/client.go
storage/client/messages.go
storage/client/queries/queries.go
storage/client/types.go
storage/migrations/13_roothash_messages.up.sql

 api: add roothash messages

---

analyzer/queries/queries.go
api/spec/v1.yaml

Fix upserting logo_url, and add an example for validator-media.

validators/metadata: fix upserting logo url

---

.changelog/730.doc.md
api/spec/v1.yaml

Closes https://github.com/oasisprotocol/nexus/issues/705
https://app.clickup.com/24394368/v/dc/q8em0-19784/q8em0-13424?block=block-d891cc72-051b-48db-bbb8-b835a8a829e3
Preview

Add a warning to total_sent and total_received fields in API docs

---

.changelog/739.bugfix.md
.changelog/740.internal.md
cmd/analyzer/analyzer.go
config/config.go
tests/e2e_regression/damask/e2e_config_2.yml
tests/e2e_regression/eden/e2e_config_2.yml
tests/e2e_regression/edenfast/e2e_config_2.yml

For consistency with other analyzers.

rename val staking history config option

---

.changelog/750.trivial.md
account-names/mainnet_paratime.json
account-names/testnet_paratime.json

Will improve readability of
- https://explorer.dev.oasis.io/testnet/sapphire/tx/41c2f1d86e5f7a0676a686260b3f881a94765d8c6f3a735bb667570d1bc1639e
- https://explorer.dev.oasis.io/testnet/sapphire/tx/0x5ab245233b9f467f55d8dba437a59fac7c9abd91b0e5cec0312686f4a87c07f5

Add subcall precompile to named accounts (and copy faucet to paratime named accs)

---

.changelog/755.feature.md
storage/client/client.go
storage/client/queries/queries.go

we do some logic similar to storage/client.fillInPrice

 storage: sort tokens by total value 

---

.changelog/810.bugfix.md
analyzer/aggregate_stats/aggregate_stats.go
analyzer/api.go
analyzer/block/block.go
analyzer/block/block_test.go
analyzer/item/item.go
cmd/analyzer/analyzer.go
cmd/analyzer/analyzer_sequencing_test.go

Fixes: https://github.com/oasisprotocol/nexus/issues/803

fix: Run PreWork once, even for parallel analyzers

---

.changelog/824.feature.md
api/spec/v1.yaml
storage/client/client.go
storage/client/queries/queries.go
storage/migrations/01_runtimes.up.sql
storage/migrations/08_runtime_transactions_method_idx.up.sql
tests/e2e_regression/common_test_cases.sh
tests/e2e_regression/damask/expected/emerald_txs_by_method.body
tests/e2e_regression/damask/expected/emerald_txs_by_method.headers
tests/e2e_regression/eden/expected/emerald_txs_by_method.body
tests/e2e_regression/eden/expected/emerald_txs_by_method.headers

Fixes: #819 
TODO: after this is merged and before deployed, apply the new index CONCURENTLY, to all deployments, to not block on deployment.

api/runtime/transactions: Support method filter

---

.changelog/880.internal.md
.github/workflows/ci-test.yaml

v3 will reach EOL on January 31st

Update actions/upload-artifact action to v4

---

.changelog/876.feature.md
storage/client/client.go
storage/client/rofl_quotes.go

https://github.com/oasisprotocol/nexus/issues/807#issuecomment-2575069694
TODO:
Example Raw Body for rofl.register transaction on localnet, with these canges:
```json
{
"app": "rofl1qqn9xndja7e2pnxhttktmecvwzz0yqwxsquqyxdf",
"ect": {
"capability_tee": {
"attestation": {
"height": 38,
"quote": {
"pcs": {
"quote": {
"header": {
"attestation_key_type": 2,
"qe_vendor_id": "k5pyM/ecTKmUCg2zlX8GBw==",
"tee_type": 0,
"version": 3
},
"report_body": {
"enclave_identity": "0+tTmlVjUvP0eIHXH7Dld3svPppCUdKDwYxnzplndLea/8+uR7hI7CyvHEm0soNTHhzEJfk1grNoBuUqQ9eNGg==",
"report_data": "m7ZsbFJbbqijr8ZNSnDv+fGnVaitH4byquxfMAwI0CIbhl6vpNqh7aI8+GRDmUqfWoRszOMNyePxwuWzm629VA=="
}
},
"tcb": {
"certs": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNpekNDQWpLZ0F3SUJBZ0lVZmppQzFmdFZLVXBBU1k1RmhBUHBGSkc5OUZVd0NnWUlLb1p …
```

runtime: Add conditional SGX attestation parsing for rofl.Register txs

---

.changelog/903.feature.md
cmd/api/api.go
config/config.go
config/config_test.go
storage/client/client.go
storage/client/queries/queries.go
tests/e2e_regression/eden/e2e_config_1.yml
tests/e2e_regression/eden/expected/emerald_tokens.body
tests/e2e_regression/eden/expected/emerald_tokens_sort_market_cap.body
tests/e2e_regression/edenfast/e2e_config_1.yml

Fixes: https://github.com/oasisprotocol/nexus/issues/900

runtime/evm_tokens: Support (partially) curated ordering

---

.changelog/906.bugfix.md
storage/client/queries/queries.go
storage/migrations/00_consensus.up.sql
storage/migrations/16_entities_address_idx.up.sql

Fixes: https://github.com/oasisprotocol/nexus/issues/905

consensus/validator_history: Optimize validator history query

---

.changelog/919.bugfix.md
.changelog/922.bugfix.md
.changelog/923.trivial.md
.changelog/925.trivial.md
.changelog/929.feature.md
.punch_version.py
CHANGELOG.md

Minor release with a couple of fixes.

changelog: Assemble changes for 0.6.2 release

---

.changelog/936.feature.md
api/spec/v1.yaml
storage/client/client.go
storage/client/queries/queries.go
tests/e2e_regression/eden/expected/emerald_failed_tx.body
tests/e2e_regression/eden/expected/emerald_txs_by_multiple_methods.body
tests/e2e_regression/eden/expected/emerald_txs_evm_call_no_native.body

https://github.com/oasisprotocol/explorer/issues/1847

api/runtime_transactions: Expose raw error message

---

.changelog/939.feature.md
api/spec/v1.yaml
storage/client/client.go
storage/client/queries/queries.go

- adds admin_eth address to rofl app response (if known)
- optimize rofl instance transactions query

storage/db: Optimize rofl instance transactions query

---

.changelog/956.trivial.md
api/spec/v1.yaml

This still causes confusion. Thoughts on this wording?

openapi: Clarify account escrow and debonding fields (for validators)

---

.changelog/959.bugfix.md
analyzer/queries/queries.go
analyzer/runtime/extract.go
storage/migrations/21_rofl_related_remove_register.up.sql

Couple of minor followups to https://github.com/oasisprotocol/nexus/pull/959

rofl instances: follow-up fixes

---

.changelog/988.feature.md
named-addresses/mainnet_sapphire.json

Related to https://github.com/oasisprotocol/nexus/pull/985

Add icons and origins of some sapphire tokens to named-addresses

---

.changelog/994.feature.md
storage/migrations/24_account_related_tranasctions_pgstats.up.sql

[…nsactionshttps://github.com/oasisprotocol/nexus/issues/993](https://github.com/oasisprotocol/nexus/issues/993)

analyzer/aggregate: Increase pg_statistic sample size for related txs

---

.changelog/997.feature.md
analyzer/queries/queries.go
analyzer/rofl/rofl.go
api/spec/v1.yaml
storage/client/client.go
storage/client/queries/queries.go
storage/migrations/19_runtime_rofl.up.sql
storage/migrations/26_runtime_rofl_metadata_name.up.sql
tests/e2e_regression/eden_testnet_2025/expected/sapphire_rofl_app_by_name.body
tests/e2e_regression/eden_testnet_2025/expected/sapphire_rofl_app_by_name.headers
tests/e2e_regression/eden_testnet_2025/test_cases.sh

Fixes: https://github.com/oasisprotocol/nexus/issues/996

api/rofl_apps: Support filtering by name

---

.changelog/1003.feature.md
api/spec/v1.yaml
storage/client/client.go
storage/client/queries/queries.go
tests/e2e_regression/damask/expected/account_with_tx.body
tests/e2e_regression/eden/expected/account_with_tx.body
tests/e2e_regression/eden_2025/expected/account_with_tx.body
tests/e2e_regression/eden_testnet_2025/expected/validator_node_account.body
tests/e2e_regression/eden_testnet_2025/expected/validator_node_account.headers
tests/e2e_regression/eden_testnet_2025/test_cases.sh

Fixes: https://github.com/oasisprotocol/nexus/issues/1000

api/accounts: Mark accounts belonging to validators

---

.changelog/1053.feature.md
analyzer/runtime/extract.go

Fixes: https://github.com/oasisprotocol/nexus/issues/1051

analyzer/runtime: Use events to detect rofl related txs

---

.changelog/1063.bugfix.md
analyzer/queries/queries.go
analyzer/roflmarket/roflmarket.go
storage/migrations/25_runtime_roflmarket.up.sql
storage/migrations/40_runtime_roflmarket_constraints_fix.up.sql

Fixes https://github.com/oasisprotocol/nexus/issues/1062 (likely)
Not sure how I missed this in the initial impl.

storage/roflmarket: Fix roflmarket tables constrains

---

.changelog/1084.feature.md
cmd/analyzer/analyzer.go
cmd/analyzer/analyzer_sequencing_test.go
cmd/api/api.go
cmd/common/common.go
cmd/common/pprof.go
cmd/root.go
go.mod
metrics/prometheus_service.go

Fixes: https://github.com/oasisprotocol/nexus/issues/1022

Cleanup services lifecycle and graceful shutdown

---

.github/workflows/release.yaml

Fixes: https://github.com/oasisprotocol/nexus/issues/1044

ci/release: Remove dockerhub

---

.changelog/1078.bugfix.md
api/errors.go
api/v1/types/util.go
storage/client/client.go

Fixes https://github.com/oasisprotocol/nexus/issues/1078

api: Return 400 on malformed input addres

---

.changelog/1105.feature.md
analyzer/queries/queries.go
analyzer/runtime/runtime.go
api/spec/v1.yaml
storage/client/client.go
storage/client/queries/queries.go
storage/migrations/01_runtimes.up.sql
storage/migrations/04_fast_sync_temp_tables.up.sql
storage/migrations/46_runtime_evm_tokens_no_events.up.sql
tests/e2e_regression/eden_2025/expected/sapphire_token_by_name.body
tests/e2e_regression/eden_2025/expected/sapphire_token_configured_addresses.body
tests/e2e_regression/eden_2025/expected/sapphire_tokens.body
tests/e2e_regression/eden_2025/expected/sapphire_tokens_sort_market_cap.body

Fixes: https://github.com/oasisprotocol/nexus/issues/1101

api/runtime/tokens: Omit num_holders and num_transfers if unknown

---

analyzer/uncategorized/evm_raw_tx.go

No change in practice, just makes the fix consistent with the fix in oasis-web3-gateway.

analyzer/evm_raw_tx: Use nil for legacy evm txs chain id

---

.changelog/1112.trivial.md
named-addresses/mainnet_sapphire.json

Add Router Protocol burn/recovery address to named accounts

---

.github/dependabot.yml

Fixes https://github.com/oasisprotocol/nexus/issues/1013

ci: Setup dependabot

---

.changelog/799.feature.md
analyzer/block/block_test.go
analyzer/item/item_test.go
analyzer/runtime/runtime_test.go
cmd/analyzer/analyzer.go
cmd/analyzer/analyzer_migrations_test.go
config/config.go
config/config_test.go
docker/nexus/Dockerfile
storage/migrations/migrations.go

Fixes: https://github.com/oasisprotocol/nexus/issues/799
TODO:

Embed migrations in the Nexus binary

---

.changelog/1038.feature.md
analyzer/consensus/data_fetch.go

Fixes https://github.com/oasisprotocol/nexus/issues/1038
Based on testing this should bring aobut 30% (~300ms) speedup in fetching consnesus blocks.

Parallelize consensus block fetching
