oasisprotocol/nexus

api/spec/v1.yaml
**Why**
Close #76 
We don't do anything cute to do variable interpolation. If we are going with Swagger validation, then we have to repeat ourselves a little more in our API definitions.
=> Update API spec

api/v1/client.go
Relates to #86.
`NULL` is a valid `EndHeight` for `Epoch` (the latest one). Apparently using a [pointer](https://github.com/jackc/pgx/issues/740) is one approach.
=> Fix ListEpochs endpoint

analyzer/consensus/consensus.go, api/v1/types.go
**Why**
Fix https://github.com/oasisprotocol/oasis-indexer/issues/86
**What**
I math-ed wrong and subtracted too many shares including the number of accrued shares in a `ReclaimEscrowEvent`.
=> Fix negative delegation shares

storage/migrations/0006_oasis_3_tx_sender_ix.sql
Hitting the `/consensus/transactions?sender=<address>` endpoint is unusably slow without this.
=> storage: Add index on tx sender

api/v1/client.go
**Why**
Relates to #92. See original issue https://github.com/oasisprotocol/oasis-indexer/issues/46 and reference https://github.com/oasisprotocol/oasis-indexer/issues/46#issuecomment-1129251832
**Expanded**
My assumption is that we want to make a single query that returns `active` and `inactive` validators aka `entities` based on their node voting power.
**TODO**
=> Fix Validator query

analyzer/consensus/consensus.go, api/spec/v1.yaml, api/v1/client.go, api/v1/types.go
**Why**
Relates to #86, #84, #87
**TODO**
=> Fix debonding delegations

analyzer/consensus/consensus.go
**Why**
I didn't recognize the difference between the two share differences. The shares returned are based on two different pools and can be pretty different.
```
{
"owner": "oasis1qru7xdwx2tkpqgv92v5gk2nmtw2z9sczq5s5w0gu",
"escrow": "oasis1qz2rxs50p4kn537tcupjhg7ad3zcm9s7uuyrrd9e",
"amount": "105001458701",
"active_shares": "88692405242",
"debonding_shares": "105001458701",
"debond_end_time": 13836
}
```
=> Fix escrow_total_shares_debonding on Account

api/v1/queries.go
**Why**
I think we lost this layer of variable interpolation, but we do have a default `ORDER`.
```
{"error":"ERROR: CASE types text and integer cannot be matched (SQLSTATE 42804)","level":"error","module":"postgres","msg":"failed to query db"}
{"err":"ERROR: CASE types text and integer cannot be matched (SQLSTATE 42804)","level":"info","module":"api","msg":"query failed","request_id":"46dd81e9-3659-4d95-9b23-cbf4a2e64cf6"}
```
=> Reference default pagination

analyzer/consensus/consensus.go, analyzer/consensus/queries.go, storage/api.go, storage/migrations/0008_oasis_3_debonding_delegation_primary_key.up.sql, storage/oasis/client.go
**Why**
Sometimes the deletion query for debonding delegation on reclaim does not work. 😡 The deployed production Indexer has this symptom.
Close again #120. See CU-3r85g3p
I was able to sometimes repro this locally by querying the `oasis_3.epochs` table while the analyzer is running, causing the deletion to return a rows affected result of `0`. Perhaps separately, we are checking the expectations of these queries. Maybe it is important or good in some future correctness checking thing.
So there are two fixes/mitigations here:
1. Add a primary key of `id` column, so that deletion is better limited to 1.
2. Move away from a `WITH QUERY` on deleting a debonding delegation row. We can have the epoch number by querying the Consensus backend, so I added that to the `StakingData`.
**Deploy** …
=> Fix debonding delegation deletion

analyzer/consensus/consensus.go, analyzer/consensus/queries.go, analyzer/consensus/workers.go, api/spec/v1.yaml, api/v1/client.go, api/v1/handlers.go, api/v1/queries.go, api/v1/types.go, api/v1/v1.go, storage/migrations/0009_agg_stats_init.up.sql
Resolves #131 
Adds a couple of basic aggregate statistics:
- Daily transaction volume
- TPS for every 5 minute interval
This can be easily extended to add any additional aggregate stats we'd want.
Note: This shouldn't be merged in until #129 goes in, since it'll introduce a number of structural changes anyway.
=> storage/migrations: Initialize framework for aggregate statistics

storage/oasis/client.go, storage/oasis/consensus.go
The oasis-client in `storage/oasis/client.go` used to store the genesisHeight, but this was overwritten in #129. Unfortunately this caused the indexer to re-fetch the genesis document on each block, resulting in a considerable (20x) slowdown in the analyzer speed. This MR thus reintroduces the cached genesisHeight in the oasis client.
=> Cache genesisHeight in source client

analyzer/consensus/consensus.go, analyzer/emerald/emerald.go, analyzer/modules/accounts.go, analyzer/modules/consensusaccounts.go, analyzer/modules/core.go, analyzer/util/util.go, analyzer/util/util_test.go
Closes #143.
Before this PR, both analyzers (consensus and emerald) over-eagerly fetched blocks. The biggest offenders:
- When the analyzers catch up with the latest block (or equivalently, round), block `latest_block+1` cannot be fetched. This was logged at the `ERROR` level, making logs full of these errors, and making it harder to find real errors. This PR demotes this kind of errors to `INFO`. It detects these errors by string matching (yikes!) the error messages generated deep inside the oasis-node and sent to the indexer via RPC any many library layers. I feel OK about the tradeoff: It would be lots of work to expose those errors in a structured way, and the only impact of potentially misparsing the error is to log it at the wrong severity level.
- Block fetching was retried with a …
=> [analyzer] Reduce logspam when caught up with the blockchain

config/docker-dev.yml, docker-compose.yml, tests/e2e/e2e_test.go
**Why**
Make Docker setup and configuration more consistent with non-Docker local development.
Increase e2e test timeout to reduce flakes.
=> Improve Docker dev and e2e test

log/log.go, storage/api.go, storage/cockroach/client.go, storage/postgres/client.go
When a SQL query fails, the existing DB interface did not allow us to log the failing query. This PR adds additional tracking and adds the failing query to the error log line.
=> [db] Log failed queries

analyzer/emerald/emerald.go, analyzer/emerald/incoming.go, analyzer/uncategorized/addresses.go, analyzer/uncategorized/eth.go, analyzer/uncategorized/evm_raw_tx.go, analyzer/uncategorized/evm_raw_tx_test.go, analyzer/uncategorized/geth_sender_pub.go, analyzer/uncategorized/helpers.go, analyzer/uncategorized/quantities.go, analyzer/uncategorized/runtimes.go, analyzer/uncategorized/visitors.go, go.mod, go.sum, storage/migrations/0011_emerald_incoming.up.sql
import from https://github.com/oasisprotocol/oasis-nexus/pull/1
=> Emerald: import parsing from nexus

analyzer/emerald/emerald.go, analyzer/queries.go, storage/migrations/0000_oasis_3_init.up.sql, storage/migrations/0009_oasis_3_emerald_init.up.sql, tests/e2e/migrations/0000_oasis_3_test_e2e.up.sql
This PR also:
- changes the type of a timestamp column to `TIMESTAMP` (from INT; used to contain unix-style timestamp)
- changes the type of `nonce` columns to BIGINT
Closes #152 
**Note: uint->int cast is left to the DB.** Details: The PR changes the type of `round` from NUMERIC (arbitrarily large integers) to BIGINT (int64). In go, rounds are `uint64`, so when we store a `round` variable into the DB, it's theoretically possible for the value to be too large. I initially coded up an explicit cast (uint->int) that panics if the uint value is too large. However I realized that the panic doesn't provide very good debugging context. OTOH if we let a value that's >=2^63 into the DB, postgres will error out, showing the query and the actual problematic value -- great for debugging. So I …
=> Emerald: Rename height->round, use BIGINT

.github/workflows/docker-indexer.yaml, .github/workflows/release.yaml
Our docker build CI action is [suddenly failing](https://github.com/oasisprotocol/oasis-indexer/actions/runs/3237922106) with `buildx failed with: ERROR: failed to solve: server message: insufficient_scope: authorization failed`.
The error is accompanied with some deprecation warnings that this PR fixes by bumping versions. My bet is that the PR will not actually solve the error, but better safe than sorry, and we need to upgrade eventually anyway.
=> infra: update github actions

api/spec/v1.yaml, storage/client/client.go
Close #102 and update documentation around status endpoint.
Move away from the fractional time displayed.
Status endpoint `https://index.oasislabs.com/v1/` returns:
```json
{"latest_chain_id":"oasis-3","latest_block":10639663,"latest_update":"2022-10-06T06:25:34.233355Z"}
```
while the block endpoint `https://index.oasislabs.com/v1/consensus/blocks/10639663` returns:
```json
{"height":10639663,"hash":"9a6b77dee42acace88583ea02ca6db2e15a38c5ce07c7a08b63ad179abaf1752","timestamp":"2022-10-06T06:25:24Z"}
```
I think we probably want to standardize the time format.
=> API: Improve latest Indexer status documentation

storage/oasis/consensus.go
We lost a change from https://github.com/oasisprotocol/oasis-indexer/pull/127/ in https://github.com/oasisprotocol/oasis-indexer/pull/129
https://github.com/oasisprotocol/oasis-indexer/blob/d02a1bed03f04c5f7d350bebad6fc5197aa0b483/storage/oasis/client.go#L141-L144
=> Fix missing Epoch in StakingData

analyzer/consensus/workers.go, storage/migrations/0010_agg_stats_init.up.sql
Closes #144 by increasing the allowed timeout for stats aggregation. To reduce DB load (and because we expect no immediate critically important uses of aggregate stats), also conservatively hugely increases the interval between consecutive runs.
Another tiny change: aggregation used to run `N*interval` seconds after analyzer start for `N>=1`. Now, it runs for `N>=0`, i.e. there's an additional run immediately when the analyzer starts. The motivation is to make debugging easier and to obtain stats faster after a new deploy.
**Testing:** Ran against a fully synced indexer db (prod :)) and confirmed the aggregation step no longer errors out.
=> aggregate stats: Increase interval, timeout

analyzer/emerald/emerald.go, analyzer/emerald/incoming.go
for #166 
from earlier discussion:
1. keep data in uint64
2. let the database complain about out of range numbers going into BIGINT
also included: convert a now-uint64 addition to use checked arithmetic. should we? or is it too ugly and unlikely
=> Emerald: eliminate uint64 -> int64 conversions

analyzer/api.go, analyzer/emerald/emerald.go, analyzer/emerald/incoming.go, analyzer/uncategorized/runtimes.go
the runtime will authenticate them for us.
the function is still fallible though... :thinking: 
not sure if there are cases where unforseen differences in Go and Rust serialization and non-authentication validation can cause us to error here
=> Emerald: don't authenticate transactions

api/spec/v1.yaml
we had a lot of these min/max filters. the queries use `>=` `<=`, so I'm entering these as inclusive
actually the time ones are kinda not right to be called simply "inclusive." if I say the max time is 2022 oct 20, that doesn't mean a block etc from 2022 oct 20 at 9 PM is "included," right? it's only if the timestamp is exactly 2022 oct 20 00:00:00 and zero microseconds, then that's equal to the provided max time and that's included. but up to 999 nanoseconds is fine because that'll be lost when it gets converted from Go to postgresql. hm.
or am I wrong about the above?
=> api: specify inclusive min/max filters

analyzer/queries.go, storage/migrations/01_oasis_3_consensus.up.sql
#192 
The validator delegations balances are slightly too low. Current hypothesis is that the rounding in `ConsensusTakeEscrowUpdateQuery` is the root cause. Since postgres `numeric` types support arbitrary precision, we should instead do the rounding at the API layer. Testing still in progress.
=> Change delegations rounding->floor

analyzer/emerald/incoming.go, analyzer/queries.go, storage/migrations/02_oasis_3_emerald.up.sql, storage/postgres/client.go
we're about to add the transactions api, where we'll want to look at the tx results. I'm proposing that we store a copy in the db so that we don't have to bother the grpc server when answering indexer clients. we do this for the transactions already, i.e. we have the inputs but not the outputs.
=>  Emerald: store transaction result 

Makefile, analyzer/consensus/consensus.go, cmd/analyzer/analyzer.go, cmd/root.go, config/config.go, storage/api.go, storage/postgres/client.go
This PR allows one to wipe the DB with a config flag:
```
analysis:
analyzers: [...]
storage:
backend: postgres
DANGER__wipe_storage_on_startup: true
```
I found it handy in my testing. It's also useful for hypothetical scenarios in staging/prod where we know we have to reindex, and a flag is better than doing manual surgery.
The PR also includes some very minor unrelated logging improvements.
=> cmd: flag for wiping the db on startup

analyzer/consensus/consensus.go, analyzer/consensus/genesis.go, analyzer/emerald/emerald.go, analyzer/modules/accounts.go, analyzer/modules/consensusaccounts.go, analyzer/modules/core.go, analyzer/queries.go, storage/migrations/01_oasis_3_consensus.up.sql, storage/migrations/02_oasis_3_emerald.up.sql
- Introduces custom types (oasis address, hash, uints, etc)
- Postgres doesn't have `uint` types out of the box, so we emulate e.g. `uint64` with `int64 CHECK (VALUE >=0)`, which is in effect an `uint63`. Emulating a proper `uint64` with a `NUMERIC CHECK (...)` is much costlier and not needed at least for now.
- Adds numerous negative-value checks (by using the `uint` types)
- Adds foreign keys where possible
- Adds comments/explanations for various tables and columns
- *breaking:* Changes the semantics of several columns that used strings such as `"unknown"` and `"0"` to indicate a special value or lack of data. These columns now use `NULL` for the same purpose; it's more idiomatic, and it allows for stronger typing.
- *breaking, bugfix:* Changes some `TEXT` columns to `NUMERIC` where …
=> Strenghten sql constraints

analyzer/consensus/consensus.go, analyzer/emerald/emerald.go, storage/migrations/01_oasis_3_consensus.up.sql
This is a forward fix for the e2e tests broken in #217.
The underlying problem was a bad uint64 cast from go to sql. The e2e test uncovered one such cast, but then I found many more. Take the following as an example:
```
batch.Queue(transactionInsertQuery, [...],
tx.Fee.Amount.ToBigInt().Uint64(),
tx.Fee.Gas, [...]
)
```
This represents both types of errors fixed by the PR:
- Amount is an arbitrary-precision int, both in core and in the db. We simply ignore any values over uint64 here. That's pretty bad, though the e2e test didn't actually catch this. 
- Gas is `uint64` in core, and `uint_numeric` (custom type, defined as `numeric(1000,0) CHECK(VALUE>=0)` ) in the db. Postgres doesn't have uint64, it only has int64. Before #217, pgx somehow recognized that the go `uint64` was being used …
=> bugfix: stringify big.Int and uint64 before sending to pgx

.github/workflows/ci-test.yaml, Makefile, docker-compose.yml, storage/postgres/client.go, storage/postgres/client_test.go, tests/e2e/config/e2e-dev.yml, tests/e2e/docker-compose.e2e.yml, tests/e2e/e2e_test.go
Various small improvements I made while working on #221:
- CI: expose container logs and DB contents as github CI artifacts
- e2e in Makefile: fix permissions so that `make stop-e2e` can clean up all the files created by `make start-e2e`. Previously, some oasis-net-runner files were created by `root` (from within a container), but in a location mounted from the host. So those were always a little clumsy to clean up.
- docker-compose: rename container `oasis-postgres` to `indexer-postgres` for consistency with non-docker-compose way of running
- postgres unit tests: fixes a typo where we referred to postgres as cockroach
- adds comments in various places
- e2e test: fix the reverted order of expected and actual values (made for weird-looking error reports)
The splitting into commits is …
=> Small readability, logging, debugging fixes

analyzer/emerald/incoming.go, analyzer/queries.go, storage/migrations/02_oasis_3_emerald.up.sql
we already have the plumbing to run something on each erc20 Transfer event. this gathers them into a token_balances table.
details:
- transfers from the zero ethereum address count as mints
- transfers to the zero ethereum address count as burns
- addresses in the table are oasis addresses. look up ethereum addresses as needed in the address preimages table
other notes:
- this doesn't count holders. I'll ask about how to implement this
- there's no enforcement about starting from genesis-----you can start whenever, and you may have negative "balance" where it only shows the total of all in-minus-out during the time scanned
- no nothin done about contracts using erc20-compatible Transfer events in any wrong way
see design https://app.clickup.com/t/3u9y034?comment=1272147909
=> Emerald: track tokens

storage/migrations/02_oasis_3_emerald.up.sql
here's the index, but I haven't made a huge table to see if the EXPLAIN is good
```
indexer=# analyze oasis_3.emerald_token_balances;
ANALYZE
indexer=# explain select token_address, count(*) as num_holders from oasis_3.emerald_token_balances where balance != 0 group by token_address;
QUERY PLAN                                   
-------------------------------------------------------------------------------
HashAggregate  (cost=6.95..7.22 rows=27 width=55)
Group Key: token_address
->  Seq Scan on emerald_token_balances  (cost=0.00..6.25 rows=140 width=47)
Filter: (balance <> '0'::numeric)
(4 rows)
```
reviewers: will this work?
=> Emerald: add index for token holders count

api/spec/v1.yaml
=> Emerald: add tokens api spec

analyzer/consensus/consensus.go, storage/api.go
Warren pointed out that our `QueryBatch.Queue` was not thread-safe. This MR aims to remedy that. Part of a broader goal of tracking down inconsistent balances/db state in #211  and #159 
I've been running a version of this locally to hunt for negative balances. No issues as of yet
=> Update concurrency of process block goroutines

cmd/root.go
This PR allows one to provide a "partial" config.yaml, e.g. without an `server:` or `analysis:` section (which configure the API server and the analyzers, respectively), and the binary will simply not run the components without a config. Before this PR, the binary would crash.
I later discovered that it is already possible to run the binary as `./analyzer analyze` or `analyzer serve`, which will make it read only one specific part of the config and thus also work with partial config files. Even so, it doesn't hurt to have the additional robustness provided in this PR.
=> Allow partial configs, optionally run just API or just analyzers

Makefile, storage/oasis/consensus.go, tests/genesis/genesis_test.go
oasis-node keeps reporting some nodes (in the `registry` part of its StateToGenesis output) even after they've already expired. Their expiration epoch is included in the output, so the output is not technically wrong; it's just not useful to insist in genesis_test that the indexer's internal state and the node's StateToGenesis agree on which _expired_ nodes should be listed.
This PR ignores expired nodes on both sides before doing a comparison.
With this fix, genesis_test passes at height 8050156 (which used to be problematic) and also at height 8055536.
The PR is motivated by #211 (so genesis_test is more reliable for finding bugs) and #179 (so genesis_test is usable for finding would-be regressions introduced by that refactor).
Vaguely related: At 8055536, genesis_test passes the …
=> bugfix: genesis_test: Ignore expired nodes in registry

storage/migrations/01_oasis_3_consensus.up.sql
Per discussion in Slack, the `transactions` table will never have a null txn_index so we tighten it. Also, the `events` table can have  a null `txn_hash`, so we adjust the fkey constraint there
=> Update fkey constraint

storage/migrations/01_oasis_3_consensus.up.sql
Updates the db fields to better match oasis-core types. 
For `account.general_balance` and `proposals.deposit`, I made them `UINT_NUMERIC` to better match the other token balance-y fields; but maybe there was a reason for not doing so originally?
=> Update db types

Makefile, docker-compose.yml, tests/e2e/docker-compose.e2e.yml
Makes it harder for devs to inadvertently step on each other's toes when pushing locally-built images. (Which is naughty in the first place and shouldn't be encouraged, but ...)
=> docker: per-user dev tags

.dockerignore, .github/workflows/ci-test.yaml, Makefile, api/common/pagination.go, api/spec/v1.yaml, api/v1/client.go, api/v1/handlers.go, api/v1/v1.go, cmd/api/api.go, docker/indexer/Dockerfile, storage/client/client.go, storage/client/queries.go, storage/client/types.go, storage/migrations/03_agg_stats.up.sql, storage/postgres/client.go
This is a collection of loosely connected commits (so reviewing commit by commit is helpful) that I did as prework for writing more HTTP APIs (#242).
The three big changes are:
- Use a template in the openapi .yaml to represent possible HTTP error codes. Functionally a no-op, and a quick change, but a large red diff.
- Render the openAPI into a .html and make it accessible through the regular HTTP API, making it self-documenting. The URL is pretty much impossible to guess though: https://index.oasislabs.com/v1/spec/v1.html
- Simplify the existing tx_volume statistic. The two granularities (stats once per 5 minutes, or stats once per hour) had wildly different names and separate implementations throughout the stack. This PR reduces duplication a lot, makes the API consistent, and …
=> openAPI: simplify stats stack, publish html version

analyzer/queries.go, storage/client/queries.go, storage/migrations/00_genesis_processing.up.sql, storage/migrations/01_oasis_3_consensus.up.sql, storage/migrations/02_oasis_3_emerald.up.sql, storage/migrations/03_agg_stats.up.sql, storage/postgres/client.go
After this PR, the API server should be able to access tables more robustly across deployments and schema migrations. 
PR fixes two problems:
- After a migration (or a wipe+regeneration of all tables), access was not granted to the new tables.
- API server was using the wrong schema.table path to some tables
Underlying issues:
- Some of our queries don't use explicit `<schema>.<table>` references to tables, using just `<table>` instead. 
The API server and the analyzer use different users (read-only vs read-write), so the API server was unable to find those tables. The default `search_path` in postgres (= schemas in order of attempted use) is `"$user", public`, so those tables ended up in different schemas for the two users.
- `GRANT SELECT ON ALL TABLES IN SCHEMA` doesn't affect the …
=> db: fix permissions, search paths

analyzer/api.go, analyzer/consensus/consensus.go, analyzer/emerald/emerald.go, config/config.go, storage/oasis/client.go, storage/oasis/client_test.go, tests/genesis/genesis_test.go
This PR speeds up startup by avoiding 1-2 queries per analyzer (= consensus/emerald/...).
Affects startup only; these are not recurring queries. They are, however, on the heftier side.
Also includes a not-really-related commit (but in the config area, where I was mucking around): There's an `Interval` param that we were not using, except in one place, when constructing the consensus analyzer. And in that one place, I'm pretty sure it was forgotten about, and actually specifying an `Interval` would crash the program.
=> Do not fetch ChainContext when known

analyzer/consensus/consensus.go, analyzer/queries.go, storage/api.go, storage/migrations/01_oasis_3_consensus.up.sql, storage/oasis/client.go, storage/oasis/consensus.go
This PR removes functionality: For a given runtime, we are now no longer able to say if it is suspended.
**Motivation:** Suspension tracking was implemented with lots of RPCs -- roughly one third of all RPCs was dedicated to this functionality. At the same time, in the short/med term, it is not really important if a runtime is suspended; we expect to hand-pick the supported runtimes, and we expect them to never be suspended. Even if we later decide that this is important real-time information to have, we could implement tracking more efficiently, but it would take refactoring (and, for the most efficient solution, an additional field in the relevant oasis-node RPC response)
**Result:** On my machine (with lots of lag), the time to process a consensus block goes from 2.93s to 2.10s. …
=> consensus: Do not track runtime (un)suspensions

analyzer/queries.go, storage/client/queries.go, storage/migrations/01_oasis_3_consensus.up.sql
Resolves https://github.com/oasisprotocol/oasis-indexer/pull/246#discussion_r1047909347
The `txn_*` naming style is used almost nowhere in the indexer or oasis-core; `tx_` is pretty much the convention. This is a breaking change, but let's live fast (and let the db die young) while we can.
=> db: Rename fields txn_* -> tx_*

api/spec/v1.yaml
Required by #88 
Part of #242
None of this is implemented yet, but I wanted us to agree on the API first. I think there are two large parts to the implementation:
- Just piping through what we already have in the DB. Most of the fields fall in this category. Still quite a bit of work because of all of our boilerplate.
- Implementing the "related addresses" field for events will require a new DB table (columns `event_id`, `related_address`; the former is a FK into `events`, which still needs a synthetic, internal-only PK id) and an extension to [this large nested `switch` statement](https://github.com/oasisprotocol/oasis-indexer/blob/d48de379c258fc467e09f33ecd614c03bfb8847d/analyzer/consensus/consensus.go#L840-L840) in the analyzer so that we'll extract whatever addresses are involved in …
=> openapi: Consensus events endpoint

api/spec/v1.yaml, api/v1/logic.go, api/v1/types.go, storage/client/client.go, storage/client/types.go
This PR adds various fields to our API that are required for an explorer MVP.
On the openapi side, some of the additions are commented out. That's because their underlying data is not something we have in the DB yet; they will therefore be more work to implement. But I want to float them here, and even merge them in their commented-out state, so that frontend folks can code against something.
**Note on account activity:**
For the "account activity" explorer page, this PR takes a double approach. In consensus, I was more ambitious and prepared #246 that sets the stage for displaying activity based on _events_. This is the preferred approach, but takes more work. But then for emerald I didn't go through with it (yet). As a lower-effort approach, I added a filter (by "related accounts") to …
=> openapi: Add assorted fields required by MVP

analyzer/api.go, analyzer/consensus/consensus.go, analyzer/queries.go, api/spec/v1.yaml, storage/migrations/01_oasis_3_consensus.up.sql
This came up in https://github.com/oasisprotocol/oasis-indexer/pull/246/files#r1048033749
Unlike the indexer, oasis-core does not have an enum of all event types. Instead, events are represented in a [nested struct that is used as a union type](https://github.com/oasisprotocol/oasis-core/blob/7f38a068c21160094ce11be1644b08cfb82b53a1/go/consensus/api/transaction/results/results.go#L13-L13). So to represent a Transfer event, for example, oasis-core use an object like `Event { Staking: { Transfer: { ... } } }`. There's no explicit enumeration/names for event types. The indexer, OTOH, needs an enum so that clients can somehow say "give me only events of type X".
Enums were named somewhat arbitrarily. They were named after the last element of the "path" in the above composite object. In …
=> event enums: Rename to conform with oasis-core

storage/migrations/01_oasis_3_consensus.up.sql
`oasis_3.blocks height` is a `UINT63`, so `oasis_3.transactions block` should be `UINT63 as well. Also updated other `BIGINT` fields that can be tightened (confirmed via oasis-core types)
=> [db] minor type fix

analyzer/consensus/consensus.go, analyzer/queries.go
Fix a foreign key constraint violation on the `allowances` table from the helpful change https://github.com/oasisprotocol/oasis-indexer/pull/217.
Our logs show:
```
["\n\t\tINSERT INTO oasis_3.allowances (owner, beneficiary, allowance)\n\t\t\tVALUES ($1, $2, $3)\n\t\tON CONFLICT (owner, beneficiary) DO\n\t\t\tUPDATE SET allowance = excluded.allowance","oasis1qq2n4alcafedvrp76sr9h8cw9y6kacxz3gtyyump","oasis1qzvlg0grjxwgjj58tx2xvmv26era6t2csqn22pte","100000000000"],
```
Hopefully this doesn't bother us here as well. I don't think so.
https://github.com/oasisprotocol/oasis-indexer/blob/825bf5046e73456cf87f95d24dc9d6433c1998d4/storage/migrations/01_oasis_3_consensus.up.sql#L191-L192
Potentially we may want to better document this behavior.
=> Add account on new allowance owner

analyzer/consensus/consensus.go
The special fee accumulator account can temporarily attain negative balance due to the order in which we process events. When that happens, the indexer grinds to a halt (first at height 8049946) because negative balances violate DB constraints.
This PR fixes the order of event processing to avoid that situation. 
An alternative solution discussed in Slack is to special-case the fee accumulator account, and not track it at all.
Another alternative (slow) is to try and change oasis-core so it returns events in the "right" order (see comment in the code diff).
*Testing:* Ran locally to height 8050256 without problems.
=> bugfix: Process fee accumulator disbursements last

api/v1/client.go, storage/client/client.go
Fixes two bugs around BigInts and the HTTP interface that I discovered accidentally:
- When parsing BigInt params, we rejected all well-formed params, and accepted others
- When we try to pass a BigInt into a DB query as a param, it fails to convert automatically and causes the query to fail. So we just have to know to convert the bigints to strings manually before passing them to the DB. Go's type system enforces/checks nothing at that layer.
While these fixes work, they are a bandaid. Proper solutions:
- (1st bug) Have a regression test that hits our HTTP API with a reasonable number of different requests. (filed #273)
- (2nd bug) Implement custom postgres serialization for BigInt (filed #274)
- (2nd bug) Refactor DB queries so that they cannot be called with arbitrarily-typed params; …
=> bugfix: Convert bigint params to string before passing to DB

analyzer/modules/evm.go, analyzer/modules/evm_test.go
okay so I'm treating three errors as deterministic (i.e. don't retry them, move on)
1. EVM "execution failed" error (code 2)
2. EVM "reverted" error (code 8)
3. if decoding the the output fails
=> Emerald: token queries, handle deterministic errors

api/spec/v1.yaml, api/v1/types/openapi.gen.go, storage/client/client.go
Fixes an oversight in original API design.
Querying `/v1/consensus/epochs` -- before (note the first epoch, i.e. the active one):
```
{"epochs":[{"id":13404,"start_height":8050156,"end_height":0},{"end_height":8050156,"id":13403,"start_height":8049556},{"end_height":8049556,"id":13402,"start_height":8048956}]}
```
After:
```
{"epochs":[{"id":13404,"start_height":8050156},{"end_height":8050156,"id":13403,"start_height":8049556},{"end_height":8049556,"id":13402,"start_height":8048956}]}
```
=> api: make epoch end height optional

storage/migrations/01_oasis_3_consensus.up.sql
@lukaw3d reported a case of a query timing out:
https://index.oasislabs.com/v1/consensus/transactions/fa0a6600c5c1c20aaf192fb0519067e250f983ea1536ee10c95b7a4f0e738a91 (exists), 200ms, 200 OK
https://index.oasislabs.com/v1/consensus/transactions/fa0a6600c5c1c20aaf192fb0519067e250f983ea1536ee10c95b7a4f0e738a92 (doesn't exist), 2min, 524 Timeout
There's nothing complex in our Go codebase, so the DB was the obvious culprit. Sure enough, there was no index on the tx hash, and I guess the fast response for the existing tx was just thanks to that tx being recent, and thus hit quickly by the postgres sequential table scan.
I added the index from this PR to both staging and prod dbs; the second query now fails quickly, as it should.
It still does not fail with 404 because of …
=> db: Add index for consensus tx hash

.github/workflows/release.yaml, Makefile
#280  introduces the use of autogenerated files that are not checked into the repo. It also fixed the CI targets to build those autogeenrated files before doign linting, building etc, but it forgot to update the CI rule for making a release.
I _think_ this PR fixes hings, but I also think the only way to verify is to merge the PR and try creating another release :/
=> bugfix: Autogenerate code before packaging a release

analyzer/consensus/consensus.go, analyzer/emerald/emerald.go
adding a timeout to 'routine' grpc requests
- https://grpc.io/blog/deadlines/#go grpc recommends using the usual go context timeout/deadline system
- #267 reports that requests freeze (thousands of minutes)
- selected timeout in this PR is 61 seconds, a little longer than the usual minute-long timeout used in common proxies
- only grpc requests are subject to the timeout. other analysis stuff including writing to the db are still able to hang \\: feel free to open an alternate PR that puts an entire loop iteration under a timeout
- not exposed in configuration :face_with_spiral_eyes: 
- 'routine' grpc requests only, exempting methods that get entire genesis documents. consensus `AllData` gives each subcomponent a timeout
=> storage: source storage timeout

api/middleware.go, cmd/api/api.go, go.mod, go.sum
Resolves #249
@lukaw3d if you're willing to test the frontend against this branch, the following should bring up a functional API server (backed by an empty DB):
```
make postgres
make oasis-indexer && ./oasis-indexer --config=config/local-dev.yml serve
```
Sample output:
```
$ curl -i -H 'Origin: example.com' 'localhost:8008/v1/consensus/blocks?limit=1'
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json
Vary: Origin
Date: Mon, 23 Jan 2023 12:48:57 GMT
Content-Length: 162
...
```
=> api: Support CORS

analyzer/emerald/incoming.go, analyzer/modules/accounts.go, analyzer/modules/consensusaccounts.go, analyzer/queries.go, storage/api.go, storage/migrations/02_oasis_3_emerald.up.sql, storage/oasis/runtime.go
Pre-work for #256 . It turns out not all data was "readily available"  :|
The PR brings two new features:
- A table with dead-reckoned balances for "oasis-sdk native" runtime balances. This is separate from Warren's work on runtime balances, which tracks ERC-20 tokens and is limited to runtimes using the `evm` module. This PR is for runtimes using the `accounts` module, which so far is all of them.
- Expands logged runtime events  (transfers, burns, mints) to include the denomination, which we completely ignored so far. Right now all runtimes only have a single denomination (ROSE or TEST), but it would be painful to expand the APIs later.
=> Track native balances in runtimes. Per-denomination events from `accounts` module. 

analyzer/consensus/consensus.go, analyzer/emerald/emerald.go, analyzer/queries.go, api/spec/v1.yaml, api/v1/logic.go, api/v1/strict_server.go, storage/client/client.go, storage/client/queries.go, storage/client/types.go, storage/migrations/01_oasis_3_consensus.up.sql, storage/migrations/02_oasis_3_emerald.up.sql, tests/e2e/e2e_test.go
Resolves #256 
Implements all the fields that were added to the API in #247.
Most of the fields were straightforward, except for runtime balances. Changes introduced there:
- Spin-off PR #288 to implement tracking of oasis-sdk balances in runtimes
- Moved `/emerald/tokens` to `/emerald/evm_tokens`; the former should be reserved for oasis-sdk tokens (currently only ROSE); internally renamed `RuntimeToken`->`EvmToken`
- Expanded `/consensus/account` to return the balances across all paratimes, simultaneously for oasis-sdk tokens and EVM tokens.
The last two points are not entirely coherent with each other: one splits the two kinds of tokens across two different URLs, while the other one unifies them. Both approaches have pluses and minuses; in the end, I decided for this combo because I …
=> api: Implement missing/empty fields for MVP

analyzer/queries.go, storage/client/client.go, storage/client/queries.go, storage/migrations/02_oasis_3_emerald.up.sql, storage/migrations/03_agg_stats.up.sql, tests/e2e_regression/reindex_and_run.sh, tests/e2e_regression/run.sh
Generalize former emerald tables so they can store data from multiple runtimes:
- adds a `runtime` column to all of them
- renames them appropriately
- udpates SQL queries appropriately
This is the first step towards https://app.clickup.com/t/3u9y285
The main benefit of this PR is that we can support new runtimes without copy-pasting `CREATE TABLE` and `CREATE INDEX` from e.g. Emerald. 
The first two commits are only vaguely related to the rest of the PR:
- The first one improves the ergonomy of e2e regression tests, so I was able to test every change.
- The second one adds an `ORDER BY` to all `SELECT` statements that use `LIMIT`. Without `ORDER BY`, an arbitrary subset is returned, which is a serious bug for windowed queries. Thanks, regression tests (they found this bug because the API …
=> Generalize emerald tables to multiple runtimes 

storage/api.go, storage/postgres/client.go, tests/genesis/genesis_test.go
As discussed on Slack, `mainnet-indexer-statecheck` (the cron job that runs genesis_test on consensus) consistently fails. A possible cause for failure is that the test creates an inconsistent snapshot of the indexer state, due to not using a strong enough DB tx isolation level.
This PR uses `SERIALIZABLE`, the strongest tx isolation level, for snapshot creation. 
More about DB tx isolation levels:
https://www.postgresql.org/docs/current/transaction-iso.html
I created a dev docker image and I'm deploying this now to see what the effect is.
```
kubectl -n monitoring create job --from=cronjobs/mainnet-indexer-statecheck manual-indexer-statecheck-mitjat
```
=> genesis-test: Create DB snapshot using full tx isolation

api/errors.go, api/middleware.go, common/types.go, storage/client/client.go, storage/client/queries.go
This PR cleans up a bunch of small things around our DB client that have been bothering me for months, but even more so lately when I've been interacting with the DB more.
Changes/improvements:
- Removes copy-pasted error logs when a SQL query fails. We log these errors in our DB wrapper library, and `pgx` proper logs them also, so they were triple-logged previously. (For QueryRow(), `pgx` design is a little different and we cannot easily have a wrapper there, so we don't log the error ourselves. Those errors used to be double-logged, and are now single-logged, by pgx.)
- Obviates manual decoding of BigInts when pulled from the DB; I added a method to `BigInt` that `pgx` can use to do the decoding automatically. It doesn't work for `*BigInt` (= API fields that are nillable) due to a pgx …
=> db client: Simplify, clean up

api/spec/v1.yaml, api/v1/strict_server.go, storage/migrations/02_oasis_3_emerald.up.sql
Notes:
- We do not support events from the `contracts` module.
- We only index the first topic (hash of event signature). This means that unsupported event types (ie anything besides erc20 transfer + approve) will not be searchable by their indexed topics other than the event signature. For supported event types, we parse and store the event params in `evm_log_params` and index this column.
=> Api spec + db changes for indexing emerald events

analyzer/emerald/emerald.go, analyzer/emerald/incoming.go, analyzer/evmtokens/evm_tokens.go, analyzer/modules/evm.go, analyzer/queries.go, cmd/analyzer/analyzer.go, storage/client/queries.go, storage/migrations/02_oasis_3_emerald.up.sql
here's a new tokens analyzer. notes from the demo:
> ~70% speedup in block scanning
**before**
**after**
---
---
=> Emerald: tokens analyzer

analyzer/aggregate_stats.go, analyzer/consensus/consensus.go, analyzer/evmtokens/evm_tokens.go, analyzer/metadata_registry.go, analyzer/runtime/incoming.go, analyzer/runtime/runtime.go, cmd/analyzer/analyzer.go, config/config.go, config/docker-dev.yml, config/local-dev.yml, storage/oasis/client.go, tests/e2e/config/e2e-dev.yml, tests/e2e_regression/reindex_and_run.sh
This PR restructures configs, with two goals in mind:
- Allow different configs (wrt their type/attributes) for different analyzers. Now that we have runtime analyzers but also various metadata analyzers, the lowest-common-denominator config structure has been getting confusing, with each analyzer using only some of its fields.
- Factor out node connection config. Previously, every runtime (+ consensus) had to specify it separately, which invites typos and discrepancies, especially with the upcoming multiple runtimes.
This is working towards https://app.clickup.com/t/3u9y285
=> analyzer: Refactor configs

storage/migrations/02_oasis_3_runtimes.up.sql
forgot to add this earlier. token_type is a value from one of those constants on the Go side
=> Emerald: add token type enum link

analyzer/queries.go, analyzer/runtime/incoming.go, api/v1/logic.go, storage/client/client.go, storage/client/queries.go, storage/client/types.go, storage/migrations/02_oasis_3_runtimes.up.sql
After this PR:
- analyzer saves block timestamp into the tx DB table (this is denormailzed, but I opted for this rather than a JOIN every time we're serving txs)
- API reads it from the DB, presents it
Resolves https://app.clickup.com/t/861maqp0p
=> /runtime/transactions: Populate the timestamp

analyzer/consensus/consensus.go, analyzer/runtime/runtime.go, cmd/analyzer/analyzer.go
constructing a runtime analyzer now takes an analyzer.Runtime parameter
cross reference #305
last (?) step of https://app.clickup.com/t/3u9y285
=> runtime: remove some Emerald references

analyzer/uncategorized/evm_raw_tx.go, analyzer/uncategorized/evm_raw_tx_test.go, analyzer/uncategorized/runtimes.go
for #305 
remove the chain ID check. it's arguably part of verifying an transaction, which we don't do in the indexer for runtimes
this makes the `decodeEthRawTx` function a little more footgun if anyone else discovers it though
=> EVM: remove chain ID check

api/middleware.go, metrics/requests.go
This is the first part of the metrics fixes -- the endpoint URLs are normalized based on a dumb but working heuristic and the latencies are now reported as a histogram.
=> metrics: Normalize endpoints, use histogram for latencies

analyzer/evmtokens/evm_tokens.go, cmd/analyzer/analyzer.go, config/config.go
for #305 
resync boilerplate with runtime analyzer.
evm tokens analyzer is now split into emerald- and sapphire-specific ones
=> evm tokens: remove Emerald references

analyzer/modules/evm.go
this had resulted in the database having zeros in the type column, making the mutate workflow fail when it sees an unknown token type
=> EVM tokens: fix missing token type

storage/migrations/02_oasis_3_runtimes.up.sql
in #310, we want to look up related addresses by transaction. add an index so that we can quickly get those and pull the address preimages
also some indexes didn't get the `runtime` column added when we unified the runtime tables in #296. adding it
=>  runtimes: add related transactions index by tx 

metrics/database.go
Use histograms for DB latency metrics as well.
=> metrics: Use histogram for DB latencies

analyzer/uncategorized/addresses.go, api/spec/v1.yaml, api/v1/logic.go, docker/node/etc/config.yml, storage/client/client.go, storage/client/queries.go, storage/client/types.go
Address https://app.clickup.com/t/3u9y3yp and add Eth address to API endpoint
=> api: Add runtime transaction sender and receiver Eth address

docker/indexer/Dockerfile
In support of https://github.com/oasislabs/private-charts/pull/552
We now copy the repo _after_ `make codegen-go` has been run in the build process.
Without the codegen files; the statecheck tests fail. We already copy the repo into the dockerfile, so the added size of the generated files is marginal.
=> include codegen files in docker image

log/log.go, log/log_test.go
Changes:
```
{"analyzer":"consensus","height":8052362,"level":"info","module":"analysis_service","msg":"processed block"}
```
To:
```
{"analyzer":"consensus","caller":"consensus.go:173","height":8052362,"level":"info","module":"analysis_service","msg":"processed block","ts":"2023-02-24T19:27:30.720709236Z"}
```
Seems like a useful thing to have.
=> log: automatically include caller and timestamp

storage/migrations/02_oasis_3_runtimes.up.sql
Based on a report from @lukaw3d where the following two queries timed out:
- https://index-staging.oasislabs.com/v1/emerald/events?tx_hash=1ada4eb14e50d7c5426f707b6d636e2222280308f09356c1cb2c14503fe927e3
- https://index-staging.oasislabs.com/v1/emerald/events?limit=1
This PR adds an index for each of those two queries.
Already applied in staging and prod DBs. Queries are fast now.
=> db: runtime_events table: add indexes

api/spec/v1.yaml, api/v1/strict_server.go, storage/client/client.go, storage/client/queries.go, storage/client/types.go, tests/e2e/e2e_test.go
Resolves #325 
Open questions:
- We'd like to support querying runtime accounts by the runtime address (eth address) as well as the consensus address. Whether or not to scope that into the MVP/this ticket is up for debate.
- Do we want to support multiple oasis-sdk balances per runtime? Doing so slightly complicates the schema (need a list of `runtimeSdkBalance`). AFAIK we only currently use 'ROSE' as the native denomination and have no plans to add more. I'd prefer to keep it simple if possible.
- Do we want to include `AccountStats` for consensus accounts if we can only show the `numTxs` for them? As Mitja pointed out, we cannot show total sent/received bc we have no consensus transfers table
Edit** 
Impl open questions:
- ~~If there is no matching entry in the `address_preimages` …
=> Add `/runtime/accounts/{addr}`; add stats to runtime account endpoint

analyzer/queries.go, analyzer/runtime/incoming.go, api/spec/v1.yaml, api/v1/logic.go, storage/client/client.go, storage/client/queries.go, storage/client/types.go, storage/migrations/02_oasis_3_runtimes.up.sql
Resolves #336 
Testing:
Manually tested locally against a production node and checked that the `gas_used` matched the value reported by the current emerald explorer. `size` is a bit more tricky to verify since the emerald explorer doesn't show it. Warren and I also briefly discussed this and it seems like the way we re-serialize transactions could possibly differ from the way the original transaction was cbor-encoded if the original transaction was serialized in a non-standard manner (which the runtime accepts). Our calculated `size` may be inaccurate in these cases, but to our knowledge this is rare.
=> api: add gas_used and size to runtime transactions

analyzer/api.go, storage/api.go, storage/postgres/client.go, tests/e2e_regression/reindex_and_run.sh, tests/e2e_regression/run.sh
Various minor fixes in preparation for https://github.com/oasisprotocol/oasis-indexer/pull/341:
- Expands e2e_regression script so it works smoothly when running&testing multiple block analyzers (e.g. consensus and emerald)
- Tweaks the mechanism via which we submit query batches to the DB; the new approach is possibly (unconfirmed) a little slower but produces more helpful error messages
- Changes the analyzer-internal Runtime enum so its underlying type is `string` rather than `int`; this way, it can be passed directly into SQL queries and pgx knows how to interpret it.
- Makes the internal `QueryBatch.Queries()` method return a more structured type (cmd and args separately), for cleaner usage and easier-to-read logs (in which queries appear when there's an error).
=> Minor fixes: improve db ergonomics, e2e testing

analyzer/aggregate_stats.go, analyzer/consensus/consensus.go, analyzer/evmtokens/evm_tokens.go, analyzer/metadata_registry.go, analyzer/modules/accounts.go, analyzer/modules/consensusaccounts.go, analyzer/modules/core.go, analyzer/queries.go, analyzer/queries/queries.go, analyzer/runtime/incoming.go, analyzer/runtime/runtime.go, storage/client/client.go, storage/client/queries.go, storage/client/queries/queries.go
Follow-up to #341 now that it is no longer required to know the ChainID to query the DB.
This PR removes the QueryFactory (QF) abstraction. It was hardly needed any more after its main parameter (chainID) was rendered obsolete. The remaining uses of QueryFactory's `runtime` field were converted so that the runtime is passed into each query as an explicit parameter.
Benefits of killing QF:
- reduces global-ish state (in QF)
- reduces number of ways in which we pass parameters into queries
- removes a layer of templated strings so SQL is easier to reason about and easier to copy-paste (for debugging etc)
A similar-to-QF lightweight templating approach remains in genesis.go. I didn't touch it because we'll majorly clean up its SQL generation (from manually stringifying args to using SQL …
=> refactor: Remove QueryFactory

analyzer/evmtokens/evm_tokens.go
if, for example, a contract is stateful and pretends to support ERC-20 when we first scan it then refuses totalSupply later, we'd crash. don't.
=> EVM: handle deterministic errors for mutated token

analyzer/modules/accounts.go, analyzer/modules/api.go, analyzer/modules/consensusaccounts.go, analyzer/modules/core.go, analyzer/runtime/runtime.go, storage/api.go, storage/oasis/runtime.go
One way to resolve #339 
This PR removes concurrency from the runtime analyzer. It also refactors the runtime analyzer to fetch all the data initially and then process it sequentially, similar to the consensus analyzer. 
Open Question:
- Should we keep the added mutex in `storage.QueryBatch`? (see the second commit) During local testing, the additional lock/unlock did not degrade the analyzer speed since the bottleneck is the network requests to the node. Although this mutex is now unnecessary, having a thread-safe `QueryBatch` would prevent this type of bug from sneaking in (again) though.
=> analyzer: remove concurrency in runtime analyzer

analyzer/evmtokenbalances/evm_token_balances.go, analyzer/evmtokens/evm_tokens.go, analyzer/modules/evm.go, analyzer/modules/evm_test.go, analyzer/queries/queries.go, analyzer/runtime/incoming.go, analyzer/uncategorized/addresses.go, cmd/analyzer/analyzer.go, config/config.go, storage/migrations/02_runtimes.up.sql
an analyzer to download token contracts' opinion of what accounts' balances are
=> EVM token balances analyzer

analyzer/consensus/consensus.go, analyzer/queries/queries.go, api/spec/v1.yaml, api/v1/strict_server.go, api/v1/types/util.go, cmd/api/api.go, config/config.go, config/docker-dev.yml, config/local-dev.yml, storage/client/client.go, storage/client/queries/queries.go, storage/client/types.go, storage/migrations/01_consensus.up.sql, tests/e2e/config/e2e-dev.yml, tests/e2e_regression/reindex_and_run.sh, tests/e2e_regression/run.sh
Testing (on some early damask mainnet blocks):
```
curl "http://localhost:8008/v1/emerald/status"
{"active_nodes":57,"latest_block":8053413,"latest_update":"2023-03-10T16:21:45Z"}
curl "http://localhost:8008/v1/cipher/status"
{"active_nodes":9,"latest_block":8053698,"latest_update":"2023-03-10T16:22:32Z"}
curl "http://localhost:8008/v1/wrong/status"
{"msg":"Invalid format for parameter runtime: not a valid enum value: wrong"}
```
This PR adds a new required parameter that needs to be included in the deployment config:
```
server:
chain_name: mainnet # (or testnet on the testnet indexer)
```
=> `{runtime}/status`: Endpoint for current number of compute nodes

analyzer/consensus/consensus.go, api/spec/v1.yaml, api/v1/logic.go, api/v1/strict_server.go, storage/client/client.go, storage/client/queries/queries.go, storage/migrations/01_consensus.up.sql
Add runtime failure details including `code`, `module`, and `message` to API response for runtime transactions.
Add failure details including `code`, `module`, and `message` to API response for Consensus transactions.
For `v1/emerald/transactions/af4c53ebbc11570a4b4fc086ea52cea48e50d6a52a0b2e81446bc54ae727baae`, we see:
```
{
"is_total_count_clipped": false,
"total_count": 0,
"transactions": [
{
"amount": "400000000000000000",
"body": {
"address": "o3KM94hIeiU9oLecNoDuhYlcBPM=",
"data": "",
"value": "BY0V4XYoAAA="
},
"eth_hash": "3db558dd0d635131ab449c2607f63f6c2d21e222de96945894c6051da9f9e769",
"fee": "2231400000000000",
"gas_limit": 22314,
"gas_used": 22143,
"hash": "af4c53ebbc11570a4b4fc086ea52cea48e50d6a52a0b2e81446bc54ae727baae",
"index": 2,
"method": "evm.Call",
"nonce_0": 788, …
```
=> api: Add runtime and Consensus transaction failure details

analyzer/runtime/incoming.go, api/spec/v1.yaml, tests/e2e_regression/run.sh
Before this PR, large-enough integer values in EVM event params were encoded as floats in the API response:
```
{"evm_type":"uint256","name":"value","value":2.70272e+22}
```
The value was correct in the DB's internal JSON representation (270272000...00) but got incorrectly serialized as a float when inserting it into the API response.
This PR changes the return type of the web API such that all integer values are represented as strings.
(first approach taken by this PR shown with ~strikeout~)
It does so by
~1. changing the internal API type of the `value` field to be `json.RawMessage`, essentially meaning "take whatever encoding the DB gives you, trust that it's valid JSON, and when you're asked to serialize yourself, just regurgitate the bytes". This makes the API correctly return …
=> bugfix: analyzer: evm events: Represent big int values as string, not float

analyzer/consensus/consensus.go, cmd/common/common.go, common/types.go, storage/api.go, storage/oasis/client.go, storage/oasis/consensus.go, storage/oasis/nodeapi/api.go, storage/oasis/nodeapi/cobalt/convert.go, storage/oasis/nodeapi/cobalt/node.go, storage/oasis/nodeapi/damask/convert.go, storage/oasis/nodeapi/damask/node.go
Resolves https://app.clickup.com/t/8669n7f27, partially resolves https://app.clickup.com/t/8669n7gt3 (for most of consensus types)
This PR:
- Implements the rest of `ConsensusApiLite` (introduced in #326), an interface that unifies communication with Cobalt and Damask nodes.
- Migrates that interface from using the latest oasis-core types to using internal types.
The latter has considerable fallout, and introduces considerable boilerplate :/. That said, it's the best solution I see. Re-posting my Slack reasoning for visibility:
>  The initial plan was to grab the Cobalt response, convert it to a Damask response, and then reuse our existing analyzer code from there. There are two issues with this:
> * It's more work than it should be. For example, in `TransactionsWithResults`, which …
=> analyzer/consensus: Full Cobalt support. Internal types for node responses.

storage/oasis/consensus.go, storage/oasis/runtime.go, tests/statecheck/consensus_test.go, tests/statecheck/runtime_test.go, tests/statecheck/util.go
Before this PR, statecheck used indexer's internal libraries to access the node. This
- Makes for less than ideal separation: Indexer proper now has methods that exist only for tests to run.
- Makes it slightly harder/messier/more boilerplate-y to refactor those libraries for multiple-version support.
This PR makes the statecheck depend on the indexer less (actually not at all, except for DB utility wrappers). It does mean that we concede we won't run statecheck on anything but the version of oasis-core and oasis-sdk that it was compiled against. Not a loss IMO; we don't need huge generality there.
Testing: None :grimacing: because it's a bit of a pain to do, and the changes are such that the compiler should have caught any problems. Also, the statecheck is not hooked up to any alerts …
=> statecheck: Do not use indexer-internal APIs for node access

storage/client/queries/queries.go
Fixes a bug where the the indexer API potentially returned a HTTP 5xx because it tried to scan a NULL address for an entity into a string. See inline comments for explanation.
The bug was introduced in https://github.com/oasisprotocol/oasis-indexer/pull/351 which changed `UPDATE chain.entities SET meta=...` into an upsert, potentially creating a new entity row with no known address. The regression wasn't caught by that PR's e2e tests because it depends on a specific sequencing of two analyzers that (can) work in parallel.
We could introduce the old behavior (UPDATE instead of upsert), but the current behavior has the advantage that we'll be able to show an entity with all its metadata as soon as we scan its registration on the chain, instead of waiting for the metadata analyzer to do its …
=> bugfix: Ignore entities with no address

storage/migrations/02_runtimes.up.sql
@csillag reported that this query was timing out:
https://index-staging.oasislabs.com/v1/emerald/transactions?limit=10&offset=0&rel=oasis1qzl89gapk5y3e8fk6x7d6zrmz2qvedjsqg6q4lxp
Further investigation revealed that the query plan was not able to use the existing indexes effectively:
```QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=1.12..5141.91 rows=10 width=658) (actual time=26604.205..50493.305 rows=10 loops=1)
->  Nested Loop  (cost=1.12..22890383.61 rows=44527 width=658) (actual time=26604.203..50493.292 rows=10 loops=1)
->  Index Scan Backward using ix_runtime_related_transactions_round_index …
```
=> add index for runtime rel tx queries

.goreleaser.yaml, analyzer/api.go, analyzer/consensus/consensus.go, analyzer/runtime/accounts.go, analyzer/runtime/consensusaccounts.go, analyzer/runtime/decode_events.go, analyzer/runtime/extract.go, analyzer/runtime/runtime.go, analyzer/runtime/visitors.go, api/v1/types/util.go, coreapi/v21.1.1/roothash/api/block/header.go, storage/api.go, storage/oasis/client.go, storage/oasis/consensus.go, storage/oasis/nodeapi/api.go, storage/oasis/nodeapi/cobalt/convert.go, storage/oasis/nodeapi/damask/convert.go, storage/oasis/nodeapi/universal_runtime.go, storage/oasis/runtime.go, tests/statecheck/runtime_test.go
This PR brings support for indexing "old" runtime blocks. Changes:
- Refactor: Extracts all runtime-related gRPC methods into a new RuntimeApiLite class. This mirrors the existing ConsensusApiLite in scope: provides 1:1 mapping to a subset of RPCs, responses are encoded in indexer-internal types. (Those types often contain fields from the latest oasis-core or oasis-sdk, so we're not fully disconnected from them, but it's a step in the right direction.)
- Tweaks GetBlock() so it supports old rounds. This is actually a Cobalt vs Damask issue, because we ask technically ask _consensus_ (specifically, its `roothash` app) for the runtime block info. And its API has changed going from Cobalt to Damask.
- Reimplements event parsing from oasis-sdk (and uses this reimplementation) such that each …
=> Support for pre-Damask runtime rounds

storage/client/client.go, storage/client/queries/queries.go
Add missing `runtime` parameter usage to query.
=> api: Fix runtime accounts query

analyzer/metadata_registry.go, analyzer/queries/queries.go, storage/client/queries/queries.go, storage/migrations/01_consensus.up.sql
This reverts commit #366 and solves the same problem in a different way: Marks the `entities.address` as NOT NULL in the consensus db, and always generates the address.
I accidentally merged #366; I wanted to address @gw0 's comment and rework the PR before merging.
See also https://github.com/oasisprotocol/oasis-indexer/pull/366#issuecomment-1490883784
Testing: Half-hearted, because it's a small change ... reindex_and_run.sh for 100 blocks just to index a few blocks and exercise the API endpoint at least once.
=> bugfix: Make entities.address NOT NULL

api/spec/v1.yaml, storage/migrations/02_runtimes.up.sql
Fixes a crash of sapphire indexer on round 144, which seems to be the first one to contain an encrypted tx.
Explanation in comments.
Testing: None, haven't figured out a tunnel to the sapphire node yet.
=> bugfix: db: Allow NULL tx body (for malformed txs)

analyzer/evmtokenbalances/evm_token_balances.go, analyzer/evmtokens/evm_tokens.go, analyzer/runtime/evm.go, analyzer/uncategorized/addresses.go, api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go
~~fixes #365~~
1. adjust some specs to use our custom string Address type
2. ~~get all related address preimage info when querying transaction~~
3. ~~don't set incorrect xxx_eth address when preimage is not secp256k1eth~~
EthAddrReference is moved out to client package. changed to EthChecksumAddrFromPreimage
=>  storage client: get entire address preimage 

storage/client/queries/queries.go, storage/migrations/01_consensus.up.sql, storage/migrations/02_runtimes.up.sql
This PR switches `JSON` to the newer `JSONB` ("JSON but Better") type. From [postgres docs](https://www.postgresql.org/docs/current/datatype-json.html):
> PostgreSQL offers two types for storing JSON data: json and jsonb. 
> The major practical difference is one of efficiency. The json data type stores an exact copy of the input text, which processing functions must reparse on each execution; while jsonb data is stored in a decomposed binary format that makes it slightly slower to input due to added conversion overhead, but significantly faster to process, since no reparsing is needed. jsonb also supports indexing, which can be a significant advantage.
> Because the json type stores an exact copy of the input text, it will preserve semantically-insignificant white space between tokens, as …
=> db: Prefer JSONB column type over JSON

analyzer/evmtokenbalances/evm_token_balances.go, analyzer/evmtokens/evm_tokens.go, analyzer/queries/queries.go, storage/migrations/01_consensus.up.sql
a preview of what it will be like to do EVM queries for downloading token data + token balances at the ~latest round instead of the last mutated round
this is for sapphire where blocks far in the past aren't accessible
tested on emerald, where I ran the block scanner over a range of blocks with token and token balance analyzers disabled then ran with only token analyzer and token balance analyzer. checked that tokens and token balances are still downloaded successfully and recorded to have been downloaded at the latest scanned block round
=> EVM: download tokens at last processed round

analyzer/runtime/runtime.go, analyzer/util/util.go, analyzer/util/util_test.go
Removes the artificial 100ms timeout before processing every block. I noticed this while working on parallelizing the block processing, and it looks to me that this timeout is unintended.
Should help with https://github.com/oasisprotocol/oasis-indexer/issues/179 - likely also affects the analysis done in that issue, since the indexer was artificially slowing itself down.
Only quickly tested consensus analyzer. On my node, this increases the consensus analyzer block process rate from:~6 per second, to: ~20 per second
=> analyzer: remove the 100ms timeout before processing every block

analyzer/aggregate_stats.go, analyzer/api.go, analyzer/evmtokenbalances/evm_token_balances.go, analyzer/evmtokens/evm_tokens.go, analyzer/runtime/evm_test.go, analyzer/runtime/runtime.go, cmd/analyzer/analyzer.go, common/types.go, config/history.go, storage/oasis/client.go, storage/oasis/nodeapi/history/history.go, storage/oasis/nodeapi/history/runtime.go, storage/oasis/runtime.go, tests/statecheck/runtime_test.go
use archive node based on runtime round
=> nodeapi: add automatic runtime history provider 

analyzer/consensus/consensus.go, storage/oasis/nodeapi/api.go, storage/oasis/nodeapi/cobalt/convert.go, storage/oasis/nodeapi/damask/convert.go
**Background:** The indexer-internal `nodeapi.Event` type that represents an oasis-core consensus event has a `Body` field. It stores the raw body of the Event as received from oasis-core, but intentionally erases the type (by using the `interface{}` type) so that the rest of the indexer doesn't need to support all the variants of Event types from all the oasis-core versions. We just dump the raw body into the DB as json, for anybody who might want to inspect it later.
**Problem:** #360 is introducing a caching layer, as part of which all oasis-core responses (= `nodeapi` types) are (de)serialized to/from the disk. The `interface{}` type does not round-trip losslessly and throws errors when deserialzing back from on-disk JSON or CBOR.
**Solution / This PR:** This PR changes the `nodeapi` …
=> nodeapi: Store raw oasis-core in serialized form

analyzer/aggregate_stats.go, analyzer/api.go, analyzer/evmtokenbalances/evm_token_balances.go, analyzer/evmtokens/evm_tokens.go, analyzer/runtime/accounts.go, analyzer/runtime/consensusaccounts.go, analyzer/runtime/evm_test.go, analyzer/runtime/runtime.go, api/middleware.go, common/types.go, config/config.go, config/history.go, storage/api.go, storage/client/client.go, storage/oasis/client.go, storage/oasis/nodeapi/file/runtime.go, storage/oasis/runtime.go, tests/statecheck/runtime_test.go, tests/statecheck/util.go
fixes #387
- ChainID: unused, removing
- Network: we no longer talk about networks, as they're too short-lived. we're letting the SDK have that term. the indexer now talks about "chains." thus we're providing a new typed string, "ChainName" for that purpose
- "consensus" as the 'runtime' in an API request context: seems unused, and I don't remember if we had anything planned for it. removing. but let me know if we shouldn't
- `.String()`: had been carried over from when these were special uint8s, but lately we're more into types that actually are strings. removing. use `string(...)` where needed
- StringifyDenomination: we mixed that into RuntimeClient because it had conveniently had the sdkPT there. but it's configuration rather than storage, and it's the only remaining thing needing the …
=> config-related cleanup and opinions

analyzer/aggregate_stats.go, analyzer/api.go, analyzer/consensus/consensus.go, analyzer/evmtokenbalances/evm_token_balances.go, analyzer/evmtokens/evm_tokens.go, analyzer/metadata_registry.go, analyzer/runtime/runtime.go, cmd/analyzer/analyzer.go, cmd/api/api.go, cmd/root.go, storage/api.go, storage/client/client.go, storage/oasis/consensus.go, storage/oasis/nodeapi/api.go, storage/oasis/nodeapi/cobalt/node.go, storage/oasis/nodeapi/damask/node.go, storage/oasis/nodeapi/file/common.go, storage/oasis/nodeapi/file/consensus.go, storage/oasis/nodeapi/file/runtime.go, storage/oasis/nodeapi/history/history.go, storage/oasis/nodeapi/history/runtime.go, storage/oasis/nodeapi/universal_runtime.go, storage/oasis/runtime.go, storage/postgres/client.go, storage/postgres/client_test.go
This PR was motivated by #360 which introduces an on-disk cache (KV store), but does not close it cleanly when exiting. This PR adds a cleanup mechanism to the cache, and (partly by necessity, partly for code hygiene) extends the cleanup mechanism to all the analyzers.
At a high level, all analyzers are now provided with an external `context.Context` in their `Start()` method, and they are on the lookout for the `ctx.Done()` channel closing. The top-level code closes the channel on regular program termination and on SIGINT (Ctrl+C).
There is an additional change piggybacking on this PR:
- The recently-added KVStore (cache) now uses `cbor` to serialize its keys. It previously used `gob`, which in my testing complained for certain keys. (I think null pointers? I didn't investigate further, …
=> analyzers, cache: Allow to shut down gracefully

storage/oasis/client.go
After #390 the clunky `runtimeInfo`/`sdkPT` config was removed, which allows us to easily instantiate a cache-based runtimeClient without attempting to connect to a node (eg in CI).
=> cleanup: enable offline cache-based runtimeClient

coreapi/v21.1.1/staking/api/api.go, storage/oasis/nodeapi/cobalt/convert.go, storage/oasis/nodeapi/cobalt/node.go, storage/oasis/nodeapi/damask/node.go, storage/oasis/nodeapi/file/common.go
This PR allows our cobalt RPC client to parse the DebondingStartEscrowEvent that was introduced mid-Cobalt.
The PR also includes some additional error message details to make this error (and similar ones) easier to pinpoint.
Prompted by https://app.clickup.com/t/866a7412t, and closes that ticket.
We've had a similar problem before: https://github.com/oasisprotocol/oasis-indexer/blob/82e29b83591b75432467ed2303a713a6d3128bc6/coreapi/v21.1.1/staking/api/api.go#L84
I believe the original sin was that when we vendored the cobalt APIs into the indexer, we took v21.1.0, which was the earliest compatible API. We should have instead gone with 21.3.9, the latest compatible one. I was wondering about it at the time but got different recommendations on slack. 
Anyway, I re-vendored v21.3.9 locally …
=> Cobalt core API: Support DebondingStartEscrowEvent

api/spec/v1.yaml
fixes https://github.com/oasisprotocol/oasis-indexer/pull/352#discussion_r1181784604
=> api: remove nonexistent required latest_chain_id

analyzer/runtime/evm_test.go, config/config.go, config/docker-dev.yml, config/local-dev.yml, storage/oasis/nodeapi/history/history.go, storage/oasis/nodeapi/history/runtime.go, tests/e2e/config/e2e-dev.yml
- one entry in `analysis.source.nodes` is no longer a NodeConfig, it's this new thing ArchiveConfig.
- ArchiveConfig is a struct with a .DefaultNode field, where you'd put the NodeConfig you used to have
- ArchiveConfig additionally has .ConsensusNode and .RuntimeNodes[runtime], which let you specify to connect to a different node for different purposes.
for operators, a config like this:
```yml
analysis:
source:
chain_name: mainnet
nodes:
damask:
rpc: grpc.oasis.dev:443
```
becomes:
```yml
analysis:
source:
chain_name: mainnet
nodes:
damask:
default:
rpc: grpc.oasis.dev:443
```
you can then add things:
```yml
analysis:
source:
chain_name: mainnet
nodes:
damask:
default:
rpc: grpc.oasis.dev:443
runtimes:
sapphire:
rpc: whatever:443
```
=> config: allow connecting to a special node for some things

analyzer/consensus/consensus.go, analyzer/evmtokenbalances/evm_token_balances.go, analyzer/evmtokens/evm_tokens.go, analyzer/runtime/runtime.go, cmd/analyzer/analyzer.go
https://app.clickup.com/t/866a6z1fg
todo: choose better var names
=> cache analyzer sources

storage/client/queries/queries.go
you ever noticed that all the eth addressed ended with '3d'? why didn't anyone say anything?
=> storage: unbreak eth address display

storage/oasis/nodeapi/file/consensus.go, storage/oasis/nodeapi/file/runtime.go
we leave the delegate api nil in that case. don't try to close it
=> file: don't crash on cleanup with query_on_cache_miss: no

analyzer/runtime/extract.go
the result is the address, not the address embedded in a 256-bit thing. just the address. don't look for 32 bytes, don't cut it.
tested on a recent evm.Create transaction that occurred on mainnet Emerald, verified that the `to` column in the runtime_transactions table was populated, verified eth addresses displayed in API against another block explorer
=> analyzer: fix evm.Create result type cutting

storage/api.go, storage/postgres/client.go
Resolves https://app.clickup.com/t/860qer9hq
Adds methods for disabling and enabling constraints.
I do not plan to add disabling/enabling indexes; it's a little nuanced what to disable (we need some of them for inserts even during fast-sync), plus they support async updates so I hope they won't slow down inserts _that_ much. To be revisited once db insertions become the bottleneck.
I think we do not need to add disabling/enabling non-FK checks, in particular non-negativity checks for balances. In fast-sync, we won't be doing any dead reckoning, so I reckon (heh) we won't produce negative balances or other values.
Very lightly tested; I just called each method a few times and verified FKs were no longer enforced. Will be better tested once we have the calling code (= fast-sync mode in …
=> db: Disable/enable FK constraints on demand

storage/oasis/nodeapi/file/common.go, storage/oasis/nodeapi/file/consensus.go, storage/oasis/nodeapi/file/kvstore.go, storage/oasis/nodeapi/file/kvstore_test.go, storage/oasis/nodeapi/file/runtime.go
[Mitja] This PR cleans up KVStore and fixes a bug in the process:
- Abstracts away fetching of a known-type value into a separate helper func
- Abstracts away the KVStore interface
- Adds unit tests (that fail the old code)
- Fixes a bug in `GetFromCacheOrCall` where if a value was in the cache, we used to not use it
- Fixes a bug in `GetFromCacheOrCall` where if a value was in the cache but couldn't be retrieved correctly (e.g. because of the wrong type), we logged too many errors
=> bugfix: KVStore (analyzer cache): Fix retrieval and error handling

config/history.go, storage/oasis/nodeapi/history/history.go
Tested locally with port-forwarding that this allows us to index testnet consensus and sapphire at the same time.
=> node config: Support testnet

.github/workflows/ci-test.yaml, cmd/analyzer/analyzer.go, cmd/analyzer/analyzer_test.go, storage/migrations/02_runtimes.up.sql, storage/postgres/client.go, storage/postgres/client_test.go, storage/postgres/testutil/testutil.go
This introduces a postgres `testutils` package, which allows connecting to the test database from other tests in the codebase. An analyzer test that executes the migrations is also included as an example of usage (the test ensures migrations are applied without errors).
This was needed/useful in https://github.com/oasisprotocol/oasis-indexer/pull/389 and was extracted into a separate PR.
=> storage: expose test postgres client and add migrations test

config/history.go
Needed for deploying without the `fast_startup: true` config option.
I got the values from oasis-sdk (the current version, and the previous via git blame). Older archives predate oasis-sdk; let's spend time digging up those chain context only if we ever do actually need them.
=> testnet config: Add expected chain contexts

analyzer/queries/queries.go, analyzer/runtime/evm.go, analyzer/runtime/extract.go, analyzer/runtime/runtime.go, common/types.go, storage/migrations/02_runtimes.up.sql
alright, if you really want to look :shrug: 
no api
philosophy:
- collapse all callformat variants into a looser type with variable size nonce+data fields.
- same for public key, there's just a variable size slot for it.
- store the format alongside, in case anyone wants to make sense of the keys+nonces+data
- the "public key" in the tx is the one provided by the caller. I'm not aware of us capturing the runtime's public key.
- if anything goes wrong, log and leave it nil. the drawback is that NULL in the db could mean either plain or something failed during analysis (e.g. new callformat that we don't support)
- kinda oddly asymmetric, we don't store the data+result when it's unencrypted
=> show us the encrypted data

analyzer/evmtokens/evm_tokens.go, analyzer/queries/queries.go, analyzer/runtime/evm.go, storage/migrations/02_runtimes.up.sql
After this PR, every smart contract we encounter has an entry in the `evm_tokens` table, with the `type` column explicitly set to `0` (signifyin "not a token") when appropriate.
**Background:**
Previously, "tokens" (smart contracts, really) that were found to not be a known/supported token type were tracked in the `evm_token_analysis` table, in that their `last_dowload_round` was nonzero ... but they were not inserted into the `evm_tokens` table, because that table only stored "true" tokens.
This led to a the `evm_token_balances` (a separate analyzer) needing access to the `evm_token_analysis` table.
In https://app.clickup.com/t/861mn3n0e, we're extending `evm_token_balances` to also query native balances. This will require some special-casing of the native token. This PR makes it so that …
=> evm_tokens: Explicitly tracks unsupported tokens in the DB

analyzer/block/block.go, analyzer/block/block_test.go, config/config.go
Adds a config parameter for configuring the batch size of the block analyzer.
The default value of 100 is likely unreasonably small for production (especially if reading blocks from cache).
I think a reasonable value for production is such that the batch processing takes 30s-1min in the expected/average case (the batch processing and lock timeouts are both 5 min). Otherwise, the "mega-query" is run unnecessarily often.
=> analyzer/block: configurable batch size

api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go
Closes: https://github.com/oasisprotocol/oasis-indexer/issues/363
=> /{runtime}/events: Include eth_tx_hash in response

analyzer/aggregate_stats.go, analyzer/queries/queries.go, storage/migrations/03_agg_stats.up.sql
Refreshing the materialized view takes ~5 min. Before this PR, the view was locked (even for read queries) during the refresh, making the related `/stats/tx_volume` endpoint unavailable for ~5min every ~1h, 1h being the refresh interval.
The changes (CREATE INDEX) have been applied to mainnet prod + staging indexers already.
Testing: Locally.
=> stats: Update materialized views concurrently

analyzer/evmtokenbalances/evm_token_balances.go, analyzer/evmtokens/evm_tokens.go, analyzer/queries/queries.go, analyzer/runtime/evm/client.go, analyzer/runtime/evm/client_test.go, analyzer/runtime/extract.go, analyzer/runtime/runtime.go, cmd/analyzer/analyzer.go, go.sum, storage/api.go, storage/migrations/02_runtimes.up.sql, storage/oasis/nodeapi/api.go, storage/oasis/nodeapi/file/runtime.go, storage/oasis/nodeapi/history/runtime.go, storage/oasis/nodeapi/universal_runtime.go, storage/oasis/runtime.go, tests/e2e_regression/e2e_config.yml
Closes https://app.clickup.com/t/861mn3n0e
I don't like how a lot of logic for native tokens is very similar to EVM tokens, so it feels like we're duplicating code, but it's just different enough that when I try to reuse snippets (or here, the whole analyzer), it ends up having a lot of parallel codepaths internally, one for EVM tokens and one for natives. Oh well. This PR is one possible balance to strike.
**Testing: **
Indexed the first 10k blocks of emerald, then ran `evm_tokens` and `evm_token_balances` analyzers. Did this both pre- and post- PR and diffed the DBs. No changes except for the new entries in `evm_token_balances_analysis` table for the native tokens.
=> evm_token_balances: Refresh balance of native tokens

analyzer/queries/queries.go, analyzer/runtime/extract.go, analyzer/runtime/runtime.go, api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go, storage/migrations/02_runtimes.up.sql
Log signatures are now stored only for parsed events. This is because only in case of parsed events, we can be sure that the thing in `topic[0]` is actually the event signature (otherwise it could be random data inserted by an anonymous event).
This makes the field a bit less useful until more EVM events will be parsed (once contract verification is supported). If the use-case for filtering arbitrary EVM events by topic is needed (regardless if verified or not), support for filtering by `topic[0]` value directly could be added to API.
Side-note:
In old code, the `evm_log_signature` was actually stored base64 encoded in the DB, which was probably unexpected. The API filtering by `evm_log_signature` did not work as described in the API docs (where hex string is used in the example). …
=> evm: only store log signatures for parsed events

storage/oasis/client_test.go, tests/statecheck/consensus_test.go, tests/statecheck/runtime_test.go, tests/statecheck/util.go
Use `require` instead of `assert` in places where continuing with tests does not make sense due to the failure (e.g. connecting to the db, querying the node etc...).  `require` is similar to `assert` but it also stops the execution of the test case, while `assert` continues.
This makes `statecheck` output a bit more readable (and meaningful) in case it fails early. 
Concrete example: if `oasisRuntimeClient.Accounts.Addresses`  failed, the `statecheck` reported a discrepancy for every account found in the postgresql db, which masked the actual error - loading the state in the first place.
=> tests: assert.Nil -> require.Nil in some places

analyzer/evmtokens/evm_tokens.go
On Testnet Production:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1109189]
goroutine 70736 [running]:
github.com/oasisprotocol/oasis-indexer/analyzer/evmtokens.Main.processStaleToken({{0x14cb622, 0x8}, {0x18b5680, 0xc000450a30}, {0x18bbc40, 0xc0003a6370}, 0xc0006ac4e0}, {0x18b39b0, 0xc000922f80}, 0xc000b771e0, ...)
/code/go/analyzer/evmtokens/evm_tokens.go:122 +0x449
github.com/oasisprotocol/oasis-indexer/analyzer/evmtokens.Main.processBatch.func1()
/code/go/analyzer/evmtokens/evm_tokens.go:170 +0x4e
golang.org/x/sync/errgroup.(*Group).Go.func1()
/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go …
```
=> evm_tokens: fix potential nil-pointer dereference

cmd/analyzer/analyzer.go
fixes #432 
second part, use the consensus 'from' block, i.e. the height at which to start indexing, decide which genesis document to use
we'll probably have to adjust this logic later when more of the fast sync functionality is ready.
=> cmd: let 'from' height choose genesis doc

Makefile
Fixes: https://github.com/oasisprotocol/oasis-indexer/issues/435
By default, `go test` will run tests from different packages concurrently in separate instances of the test binary. Since we have tests that use the local postgresql instance in multiple packages, make sure these are not run concurrently.
The CI `Go Build` step time increases from 3 to 5 minutes in CI.
=> tests: don't run tests concurrently

analyzer/runtime/runtime.go, storage/api.go, storage/api_test.go
Fixes: https://github.com/oasisprotocol/oasis-indexer/issues/439
An alternative would be to change the error_message field to `bytea`, but it seems that non-utf8 encodable error messages are the exception rather than the norm, so maybe it makes more sense handling it this way?
Could also prefix it with "hex-encoded" or something.
=> runtime: error message does not need to be a valid utf-8

analyzer/evmtokens/evm_tokens.go
the embedded *EVMTokenMutableData struct is nil, so it's illegal even to check if TotalSupply is nil
=> evmtokens: check for nil EVMTokenMutableData

analyzer/queries/queries.go, analyzer/runtime/extract.go, analyzer/runtime/runtime.go, storage/client/queries/queries.go, storage/migrations/02_runtimes.up.sql
Filtering runtime events by `eth_tx_hash` (included in: https://github.com/oasisprotocol/oasis-indexer/pull/419)
Caused a regression in get events API call performance: e.g.: https://index.oasislabs.com/v1/emerald/events?tx_hash=14674280e2b569122ff350f6cede43ad340d698dc9796f9d1bbc6d59622b7dc8&limit=100 gets stuck.
This is the query plan for the query made by the above requests:
```
Aggregate  (cost=9283853.87..9283853.88 rows=1 width=8)
->  Limit  (cost=9283828.81..9283851.44 rows=194 width=212)
->  Gather Merge  (cost=9283828.81..9283851.44 rows=194 width=212)
Workers Planned: 2
->  Sort  (cost=9282828.79..9282829.03 rows=97 width=212)
Sort Key: evs.round DESC, evs.tx_index, evs.type, ((evs.body)::text)
->  Parallel Hash Left Join  (cost=6858208.35..9282825.59 rows=97 width=212)
Hash …
```
=> analyzer: runtime_events evm-tx hash query optimisation

storage/client/queries/queries.go
reported by @csillag 
tested locally on a sequence of ~200 blocks in mainnet emerald with known token activity
=> storage: read token name

api/errors.go, api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go
**Bugfix:** The /{runtime}/evm_tokens endpoint had the token `type` as a required field for each token. However for some tokens, we cannot heuristically determine the type (or it's a currently unsupported type; currently, only ERC-20 is supported), and the field will be null there.
This PR changes how we fetch the tokens so that unknown-type tokens are suppressed.
The PR applies the same fix to `/{runtime}/accounts/{address}`, field `evm_balances`, which used to include unsupported-type tokens.
I noticed the error when https://testnet-index.oasislabs.com/v1/sapphire/evm_tokens produced an error:
`can't scan into dest[6]: cannot scan NULL into *string`, with a SQL statement `SELECT ... FROM chain.evm_tokens` where `dest[6]` is the type.
**Bonus bugfix:**
The actual error above was hidden …
=> api: EVM tokens: output only tokesn of supported types; fix error generation

api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go
This PR exposes two new fields in the contracts API:
- the newly-added runtime_bytecode field (see #448)
- exadds the eth variant of the originating tx's hash
Testing: Manually ran the new analyzer, then visited a contract address and a non-contract address and verified that the new field is as expected.
=> api: /{runtime}/accounts/{addr}: Show contract runtime bytecode, show eth address of originating tx

analyzer/block/block.go, analyzer/queries/queries.go, storage/client/queries/queries.go, storage/migrations/01_consensus.up.sql, storage/migrations/02_runtimes.up.sql, storage/migrations/05_evm_runtime_bytecode.up.sql, storage/migrations/06_analysis_schema.up.sql, tests/statecheck/util.go
Internal refactor. This PR moves analysis DB tables (= those with analyzer-internal info) into their own `analysis` schema, introduced in #448.
Testing: Ran for 2000 blocks with all analyzers; no errors were produced.
=> db: Move analysis tables to their own schema

api/spec/v1.yaml, api/v1/strict_server.go, storage/client/client.go, storage/client/queries/queries.go
This PR adds a new endpoint for retrieving token-specific details about a single token contract.
I was initially planning to put this info under a field in the `/{runtime}/accounts/{address}` endpoint, but then decided to put it here as that endpoint's response is pretty heavy already.
There's not a task/issue for this PR, but I expect it to be needed in the near future as the explorer will show info about individual token-like contracts. cc @csillag
Testing: Manually visited an url of a token contract, verified the info was there. Visited a non-token contract, verified I got HTTP 404.
=> api: Add /{runtime}/evm_tokens/{address} endpoint

api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go, tests/e2e_regression/expected/emerald_status.body, tests/e2e_regression/expected/status.body
Resloves https://app.clickup.com/t/866af85d2
Testing (locally):
```
curl "localhost:8008/v1/"
{"latest_block":8049056,"latest_block_time":"2022-04-11T13:12:48+02:00","latest_update":"2023-06-25T09:20:13+02:00"}
curl "localhost:8008/v1/emerald/status"
{"active_nodes":0,"latest_block":1004425,"latest_block_time":"2022-04-11T17:04:34+02:00","latest_update":"2023-06-25T09:18:49+02:00"}
```
=> status: Expose datetime of most recent block

api/spec/v1.yaml, api/v1/strict_server.go, storage/client/client.go, storage/client/queries/queries.go, storage/client/types.go
This PR adds a new endpoint that lets clients retrieve the list of token holders for non-native tokens.
It is implemented as a separate endpoint because the most popular token in mainnet emerald has ~23k holders, so we need pagination.
Minor: The PR also updates the recently added `evm_contract_addr` field in the endpoint that lists EVM tokens: It renames it to `eth_*` (the preferred prefix, I believe) and applies checksum capitalization.
Testing (in local DB):
```
-- Get top-held tokens
indexer=# SELECT token_address, COUNT(*) AS cnt FROM chain.evm_token_balances where runtime='emerald' group by 1 order by 2 desc;
token_address                  | cnt 
------------------------------------------------+-----
oasis1qzw6wua8kc6jmjef6trm8mndqnuuyg7cpcjxt0e2 | 429 …
```
=> Add /evm_tokens/{address}/holders endpoint

analyzer/consensus/genesis.go
This PR slightly expands genesis processing: We now also populate the `chain.runtime_nodes` table from the genesis.
While working on https://github.com/oasisprotocol/oasis-indexer/pull/457, this was the only piece of data that could/should be extracted from genesis (because it's available in the genesis, and interesting in that we track it during block processing), but is not.
This table is also the basis for the "active nodes" query which is used by the Explorer to show the number of nodes supporting each runtime: https://github.com/oasisprotocol/oasis-indexer/blob/4a5120057ec008e8b40ce18f4b8068716eb47318/storage/client/queries/queries.go#L500-L504
Once this PR and https://github.com/oasisprotocol/oasis-indexer/pull/456 (which will introduce the use of `GenesisAtHeight()`) are both …
=> analyzer: genesis: parse compute nodes for each runtime

storage/migrations/01_consensus.up.sql, storage/migrations/02_runtimes.up.sql, storage/migrations/05_evm_runtime_bytecode.up.sql
All custom DB types defined by the `indexer` DB user were by default created in the `indexer` DB schema. The `api` (readonly) DB user was unable to see and use them. A recent change introduced a query with `$1::oasis_addr` on the API side, and that failed with `storage error: storage error: ERROR: type \"oasis_addr\" does not exist`. It's surprising to me that this happened only now.
This PR changes the definitions of custom types so that they live in the `public` schema. This makes them publicly viewable. The more principled solution would be to put them into the `chain` schema, but then we'd need things like `$1::chain.oasis_addr` everywhere (or we'd need to include `chain` in the `search_path`, which I'm not a fan of because it makes behavior more hidden).
I verified that the DB wiping …
=> bugfix: db: Make custom types public

api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go
tested locally on ~500 blocks from Emerald. very few tokens though
=>  api: allow filter EVM tokens by name

analyzer/evmabi/contracts/ERC165.sol, analyzer/evmabi/contracts/ERC721.sol, analyzer/evmabi/contracts/artifacts/ERC165.json, analyzer/evmabi/contracts/artifacts/ERC20.json, analyzer/evmabi/contracts/artifacts/ERC721.json, analyzer/evmabi/contracts/artifacts/ERC721Enumerable.json, analyzer/evmabi/contracts/artifacts/ERC721Metadata.json, analyzer/evmabi/contracts/artifacts/ERC721TokenReceiver.json, analyzer/evmabi/evmabi.go, analyzer/runtime/evm/client.go, analyzer/runtime/evm/client_test.go, analyzer/runtime/evm/erc165.go, analyzer/runtime/evm/erc165_test.go, analyzer/runtime/evm/erc20.go, analyzer/runtime/evm/erc721.go, analyzer/runtime/extract.go, analyzer/runtime/visitors.go, storage/client/queries/queries.go
functionality:
- token scanner can detect ERC-721 using ERC-165 supportsInterface
- block scanner can detect ERC-721 events and schedule token scanning
- schedules 'mutable' parts rescan (i.e. total supply) when tokens are minted
- registers transaction related accounts when seeing events
not included:
- approvals tracking (similar to that not being supported for ERC-20)
- tracking ownership of tokens
- holders count
tested on recent blocks on emerald, where a BlockchainCuties transfer had occurred
=> ERC-721 support

analyzer/runtime/evm/client.go, analyzer/runtime/evm/erc721.go, analyzer/runtime/extract.go
the "balance" is the number of the tokens they have, i.e. exactly one moves per Transfer event. this will help us show the number of holders
tested with the same block range as #447
=> analyzer/runtime: enable balance tracking for ERC-721

storage/postgres/client.go
run the deferred `rows.Close()` earlier
=> storage: move some wipe logic out to functions

api/spec/v1.yaml
Looking at the code [here](https://github.com/oasisprotocol/nexus/commit/f29b2db3a6cc1bdb5ddc358de51e52cc34ba5855#diff-c50bc5e7bf70c6477e2cfbc66d3d6130ffcf0dd9060ba20bc63a129edb477b29R469), I think we are returning matches in the token symbol, not only in the token name. (Which is perfect.) I think the description of the parameter should reflect that.
=> Update parameter description to better match behavior

api/spec/v1.yaml, storage/client/client.go, tests/e2e_regression/expected/emerald_txs.body
Resolves https://app.clickup.com/t/866ahv3h0
We cannot know if an `evm.Call` tx transfers native runtime tokens or not, but we can expose a heuristic that all clients will consume.
This PR adds an `is_likely_native_token_transfer` field to the runtime tx output, with that heuristic.
=> /{runtime}/transactions: Add heuristic field for "is tx a native token transfer?"

tests/statecheck/runtime_test.go
The balance check was broken as it was comparing different types:
```
actual  : common.BigInt(common.BigInt{Int:big.Int{neg:false, abs:big.nat{0x6cc752931729f680}}})
expected: *big.Int(7838324468163933824)
```
Additionally, there was a duplicated/wrong additional `assert` outside the `if` statement.
=> statecheck/runtime: fix balance checks

api/spec/v1.yaml
Support for this token type has been re-enabled by #447 and #459, but the API specification needs to be updated, too.
=> Re-enable ERC-721 token type in the API specs

analyzer/runtime/evm/client.go
had only hooked up the method for downloading new tokens. mint/burn will cause us to reconcile the "mutable" total supply, which needs a case here
=> analyzer/evm: handle downloading ERC-721 mutable data

storage/client/queries/queries.go
Noticed that the queries to `/v1/` and `/v1/{runtime}/status` were slow during the load tests. 
Within the staging db: 
```
oasisindexer=> explain analyze SELECT height, processed_time
FROM analysis.processed_blocks
WHERE analyzer='consensus' AND processed_time IS NOT NULL
ORDER BY processed_time DESC
LIMIT 1;
QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=122859.34..122859.46 rows=1 width=16) (actual time=1532.263..1533.708 rows=1 loops=1)
->  Gather Merge  (cost=122859.34..389035.66 rows=2281352 width=16) (actual time=1532.261..1533.704 rows=1 loops=1)
Workers Planned: 2
Workers Launched: 2
->  Sort  (cost=121859.32..124711.01 rows=1140676 width=16) (actual …
```
=> [db] add index to improve /status queries

analyzer/evmcontractcode/evm_contract_code.go, analyzer/evmtokenbalances/evm_token_balances.go, analyzer/evmtokens/evm_tokens.go, analyzer/queries/queries.go
sample output:
```
evm_contract_code_emerald_queue_length 0
evm_token_balances_emerald_queue_length 0
evm_tokens_emerald_queue_length 0
```
it runs kinda fast locally so I don't have a copy with nonzero values
=> paratime analyzers other than block analyzer, queue length metric

analyzer/evmtokens/evm_tokens.go, analyzer/runtime/evm/erc721.go
Error logs from production testnet: 
```
{"caller":"grpc.go:242","err":"reverted: no revert reason","level":"error","method":"/oasis-core.RuntimeClient/Query","module":"grpc/client","msg":"request failed","req_seq":691,"rsp":{"data":null},"ts":"2023-07-17T23:08:52.727908865Z"}
{"analyzer":"evm_tokens_sapphire","caller":"client.go:179","contract_eth_addr_hex":"3d040c42f8159bfbd87a0acc436b2ed7a54955d0","err":"runtime client evm simulate call: reverted: no revert reason","interface_id":"01ffc9a7","interface_name":"ERC165","level":"info","method":"supportsInterface","module":"analysis_service","msg":"call failed","round":1909247,"ts":"2023-07-17T23:08:52.727998191Z"}
{"args":["sapphire","oasis1qzk5pr2x8ah04lgjee3lv06fmyvqvz45egjv4ps0","<nil>"],"caller":"client.go:60","db":"oasisindexer","err": …
```
=> analyzer: bugfix download erc721 mutable data

cmd/root.go
Resolves https://app.clickup.com/t/866ahha15
This PR maxes the `nexus` binary respond to the `SIGUSR1` os signal by logging the stack traces of all goroutines.
A good way to read the stack traces is to pass the (last minute of) logs through on of:
```
| jq -r  '.goroutines_all | select(.)'
| jq -r  '.goroutines_block | select(.)'
| jq -r  '.goroutines_mutex | select(.)'
```
Motivation:
Currently, the only way to obtain the stacks of goroutines is to send a SIGQUIT, which also terminates the program. And in a way that does not safely close the KVStore , at that. When analyzers get inexplicably stuck (see e.g. https://app.clickup.com/t/866ahh8xy), the list of goroutines can be very helpful for diagnosing the live system.
Tested locally.
=> cmd: Log goroutines (stack traces) on SIGUSR1

api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go
According to the [openapi spec](https://github.com/oasisprotocol/nexus/blob/main/api/spec/v1.yaml#L1748), the token_contract_address in `RuntimeEvmBalance` should be the EVM address and not the oasis address. 
Need to confirm with explorer team that the currently returned oasis address can be replaced by the evm address. If not, we can return both the oasis and evm addresses (though the oasis address can be derived from the eth address).
=> [api] return evm address instead of oasis addr in RuntimeEvmBalance

analyzer/queries/queries.go, analyzer/runtime/runtime.go, storage/migrations/02_runtimes.up.sql, storage/migrations/09_evm_token_total_supply.up.sql
The testnet sapphire indexers stalled at block 2025715 due to 
`{"args":["sapphire","oasis1qqlhksazqvm5tgt9pr3csf6dzmgy9d904qpza6vy","-1",2025715],"caller":"client.go:60","db":"oasisindexer","err":"ERROR: value for domain uint_numeric violates check constraint \"uint_numeric_check\" (SQLSTATE 23514)","level":"error","module":"postgres","msg":"Query","pid":119862,"sql":"\n    INSERT INTO analysis.evm_tokens (runtime, token_address, total_supply, last_mutate_round)\n      VALUES ($1, $2, $3, $4)\n    ON CONFLICT (runtime, token_address) DO\n      UPDATE SET \n        total_supply = analysis.evm_tokens.total_supply + $3,\n        last_mutate_round = excluded.last_mutate_round","time":"1.929012ms","ts":"2023-07-28T09:55:42.734831909Z"}`
The underlying cause was that the `total_supply` column …
=> update total_supply to accept negative updates

analyzer/runtime/evm/client.go, analyzer/runtime/extract.go, analyzer/runtime/runtime.go
The analyzer crashed with 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x64bc9d]
goroutine 127299 [running]:
math/big.(*Int).Add(0x0, 0x1?, 0xc0000ab2f0?)
/usr/local/go/src/math/big/int.go:116 +0x1d
github.com/oasisprotocol/nexus/analyzer/runtime.extractEvents.func4.3({0xc000644b0c, 0x14, 0x14}, {0xc000644b2c, 0x14, 0x14}, {0xc000644b40?, 0xc000602858?, 0x69fab4?})
/code/go/analyzer/runtime/extract.go:764 +0x5e5
github.com/oasisprotocol/nexus/analyzer/runtime.VisitEVMEvent(0xc0000a5b30, 0xc000602e08)
/code/go/analyzer/runtime/visitors.go:215 +0x7b9
github.com/oasisprotocol/nexus/analyzer/runtime.extractEvents.func4(0xc0000a5b30)
/code/go/analyzer/runtime/extract.go:633 +0x456 …
```
=> bugfix: initialize possibleToken fields

storage/client/queries/queries.go, storage/migrations/02_runtimes.up.sql, storage/migrations/10_runtime_address_preimage_idx.up.sql
@lukaw3d pointed out that the `/events` endpoint was slow. Root cause was the left join on `address_preimages` in order to look up token-specific information for events.
=> add index for chain.addres_preimages.address_data

analyzer/pubclient/pubclient.go, analyzer/pubclient/pubclient_test.go
soon we'll be fetching NFT metadata. here's an http.Client that only connects to public IP addresses
based on the approach described here: https://www.agwa.name/blog/post/preventing_server_side_request_forgery_in_golang
uses oasis-core's IsProbablyGloballyReachable https://pkg.go.dev/github.com/oasisprotocol/oasis-core/go/common#IsProbablyGloballyReachable
=> analyzer: add pubclient

storage/oasis/nodeapi/api.go, storage/oasis/nodeapi/cobalt/convert.go, storage/oasis/nodeapi/compat_types.go, storage/oasis/nodeapi/damask/node.go
Bugfix for accessing cobalt state. I don't know how we didn't hit this problem before.
**Problem**
The CommitteeKind type (which is used inside committee updates at the consensus layer) is an enum, with **three** possible values in cobalt, but only **two** possible values in damask. Before this PR, we were using the damask type. So when trying to serialize an enum value that comes from cobalt and is valid in cobalt but not in damask, an error was raised.
**Solution**
This PR creates a new type that's independent of cobalt and damask (even though it's technically just copy-paste from cobalt), but is compatible with both. 
No data changes are needed (caches, db, etc). The new type is byte-compatible with the type we've been using. Just the serde methods are able to accept the extra enum …
=> nodeapi: Make CommitteeKind compatbile across cobalt and damask

storage/migrations/02_runtimes.up.sql, storage/migrations/13_runtime_indexes.up.sql
@lukaw3d found that the `/events` endpoint was slow when a related account was not specified in the query (`rel=oasis12345`). The `explain analyze` of the query:
```
oasisindexer=*> explain analyze SELECT
evs.round,
evs.tx_index,
evs.tx_hash,
evs.tx_eth_hash,
evs.timestamp,
evs.type,
evs.body,
evs.evm_log_name,
evs.evm_log_params,
tokens.symbol,
CASE -- NOTE: There are three queries that use this CASE via copy-paste; edit both if changing.
WHEN tokens.token_type = 20 THEN 'ERC20'
WHEN tokens.token_type = 721 THEN 'ERC721'
ELSE NULL -- Our openapi spec doesn't allow us to output this, but better this than a null value (which causes nil dereference)
END AS token_type,
tokens.decimals
FROM chain.runtime_events as evs
-- Look up the oasis-style address derived from evs.body.address.
-- The …
```
=> Adjust chain.runtime_events indexes

storage/migrations/11_agg_stats_refactor.up.sql
New tables were introduced in https://github.com/oasisprotocol/nexus/pull/477/files, but we forgot to set permissions for them.
This has already been fixed/applied manually in our existing deploys by @ptrus
=> bugfix: db: grant permissions on new tables

analyzer/uncategorized/evm_raw_tx_test.go
- return from sdk `helpers.EthAddressFromPubKey` is now go-ethereum `common.Address`, which I've been calling "ecAddr" (see reference https://github.com/oasisprotocol/nexus/blob/v0.1.11/analyzer/uncategorized/addresses.go#L14).
- no longer have to work backwards from 0x-prefixed checksum-capitalized string, so all we have to do is `hex.EncodeToString`
=> analyzer: rename from0xChecksummed following sdk change

analyzer/runtime/decode_events.go, analyzer/runtime/visitors.go
This PR adds suppport for parsing (the new event codes present in) Sapphire 0.6.0 blocks; it is a follow-up to #508 which was not possible to test at the time.
It was not enough to just import the newer type definitions (as #508 did), we also had to add some handling for the new types (as this PR does).
Testing: Indexed the offending block 2_378_823 of sapphire testnet. (Now the internal testnet node is working again, so I was able to test properly.)
=> analyzer/runtime/consensusaccounts: Handle new client-sdk 0.6.0 event codes

analyzer/runtime/runtime.go
I found this while reading through the (de)bonding code in the runtime-sdk.
I'm not sure these address preimages are even surfaced anywhere in our API (because they're not eth preimages), but it can be helpful to have them when interpreting/debugging txs and events manually.
Related thought: It _would_ be nice to surface these on the frontend also. Since it's a small set of completely static addresses, I think it's best to keep it simple and hardcode them in the frontend code somewhere.
=> analyzer/runtime: Register special runtime addresses

analyzer/consensus/consensus.go, analyzer/queries/queries.go
Previously, the analyzer halted if it encountered more than one vote ever for the same (proposal, voter) pair.
This happens in block 4637995:
```INSERT INTO chain.votes (proposal, voter, vote)
VALUES ($1, $2, $3) [1 oasis1qq0xmq7r0z9sdv02t5j9zs7en3n6574gtg8v9fyt yes]}: ERROR: duplicate key value violates unique constraint "votes_pkey"```
=> bugfix: analyzer/consensus: votes: upsert instead of insert

analyzer/runtime/evm/client.go, storage/oasis/nodeapi/api.go, storage/oasis/nodeapi/evm.go, storage/oasis/nodeapi/file/kvstore.go, storage/oasis/nodeapi/file/runtime.go, storage/oasis/nodeapi/history/runtime.go, storage/oasis/nodeapi/universal_runtime.go
https://app.clickup.com/t/8692qau0v
Updates `EvmSimulateCall` to return a wrapped result that can also include a known error.
Testing: Ran the e2e_regression tests with non-block analyzers locally; no issues with running in offline mode.
random thoughts:
- Decided against using FallibleResponse for all node queries since it introduces a lot of unnecessary bloat/boilerplate.
- Think more about how/when we actually want to cache node errors. Are there any cases of `EvmSimulateCall` that might error 'deterministically' but later succeed? ---- No, since `EvmSimulateCall` is queried at a given `round`
- For evm.Code, we currently ignore any errors and retry later, which means that we don't want to cache the error (except maaybe in testing environs). --- Yes, the only errors evm.Code will …
=> nodeapi: cache deterministic failure responses

analyzer/runtime/extract.go, analyzer/runtime/visitors.go, api/spec/v1.yaml
Adds indexing of txs that call the `consensus.Delegate` and `consensus.Undelegate` methods, and of `consensus_accounts` SDK events of type `Delegate`, `UndelegateStart`, `UndelegateDone`.
TODO: Testing. For starters, I'll run this on the last few weeks of data on testnet, which is where these txs and events first appeared.
=> analyzer/runtime: Index (un)delegate events, txs

analyzer/evmtokens/evm_tokens.go, analyzer/queries/queries.go
https://app.clickup.com/t/8692rqgz6
The root cause was that the `Oasis Swag EthCC 6` evm token on sapphire testnet would return a `nil` totalSupply. The resulting code path would not return an error or update `last_download_round`. This PR ensures that `last_download_round` is always updated unless an error occured.
=> always update last_download_round for evm_tokens

api/v1/strict_server.go, storage/client/client.go, storage/client/queries/queries.go
I noticed a bunch of duplicated code for fetching a single validator, or a list of validators. In both cases, we return the same level of detail, i.e. same fields.
Testing: regression_e2e over 1000 blocks. (Including db dumps; not available in `main` yet)
=> api: Simplify validator queries (no-op)

analyzer/runtime/extract.go
Resolves https://github.com/oasisprotocol/nexus/issues/445
don't pass tx.result to evmMaybeUnmarshalEncrypted for evm.Create calls bc its the address of the created contract, which is already stored as `tx.To`.
Todo:
- Think about backfilling. It can't be done with a simple db migration; it almost certainly requires a full reindex
- During the early days of testnet there were some encrypted sapphire evm.Create txs that have a cbor-encoded callResult. There are 360 of these txs ranging from blocks 2293->5023 on testnet. [Sample tx](https://explorer.dev.oasis.io/testnet/sapphire/tx/0x669d9e79702eef3b1347f7b846331dab0bc0751f3859b42dc998a432147e9c4a) After this PR, the encrypted result data/nonce will no longer be available. In lieu of complicating the code with a special case to extract the …
=> Parse encrypted evm.Create txs correctly

storage/oasis/nodeapi/file/kvstore.go, storage/oasis/nodeapi/file/kvstore_test.go
Fixes silly typo that resulted in less-readable error messages (as recently seen on slack) about invalidly-typed cache values.
=> bugfix: kvstore: Error messages do not decode the key correctly

analyzer/aggregate_stats/aggregate_stats.go, analyzer/consensus/consensus.go, analyzer/runtime/runtime.go, api/middleware.go, metrics/database.go, metrics/requests.go, metrics/storage.go, storage/oasis/nodeapi/file/consensus.go, storage/oasis/nodeapi/file/kvstore.go, storage/oasis/nodeapi/file/kvstore_test.go, storage/oasis/nodeapi/file/runtime.go
See title. This will be nice to have: We can make better sense of speed-of-indexing grafana charts if we know whether node I/O is involved.
This PR also includes a cleanup commit that enforces strong typing for labels when accessing metrics, and renames local variable that represent metrics so that the variable name matches the metric name. **I recommend reviewing that first commit separately** -- lots of noise, not much effect.
=> kvstore: Add prometheus metric for cache hits/misses

analyzer/evmnfts/evm_nfts.go, analyzer/evmtokenbalances/evm_token_balances.go, analyzer/evmtokens/evm_tokens.go, analyzer/queries/queries.go, analyzer/runtime/evm/client.go, analyzer/runtime/evm/erc20.go, analyzer/runtime/evm/erc721.go, common/token_types.go, storage/client/client.go, storage/client/queries/queries.go
=> storage: move token type translation to go

cmd/analyzer/analyzer.go, config/config.go
replicating the emerald version
=> config: add evm_nfts_sapphire

analyzer/api.go, cmd/analyzer/analyzer.go, cmd/analyzer/analyzer_migrations_test.go, cmd/analyzer/analyzer_sequencing_test.go, cmd/analyzer/analyzer_test.go
This PR changes the sequencing of analyzers to what the title describes.
Previously, _all_ slow-sync analyzers were started only once _all_ fast-sync analyzers completed. But it doesn't make sense for e.eg. Sapphire to wait for fast-sync consensus to complete. These arbitrary delays were expecially noticeable when doing a full reindex (where fast-sync can take a week or more), or if one of the runtimes/consensus encountered an error during fast-sync and got stuck.
Resolves https://app.clickup.com/t/8692uz0a5
=> analyzer: Slow-sync analyzers wait only for _relevant_ fast-sync analyzers to complete

Makefile, config/config.go, storage/oasis/client.go, storage/oasis/connections/raw_grpc.go, storage/oasis/nodeapi/cobalt/node.go, storage/oasis/nodeapi/damask/node.go, storage/oasis/nodeapi/history/history.go, storage/oasis/nodeapi/history/runtime.go, storage/oasis/nodeapi/universal_runtime.go, tests/e2e_regression/e2e_config_1.yml, tests/e2e_regression/e2e_config_2.yml
Before this PR, nexus connected to all the oasis nodes listed in the config immediately on startup, and failed to start if any of the nodes were unavailable.
This PR makes nexus connect to the nodes lazily, on-demand.
This has multiple benefits:
- **More robust startup**; e.g. a downed Sapphire node does not stop us from indexing consensus. (Before, indexing consensus in this scenario required temporarily disabling Sapphire in the config.)
- Of short-term interest: We should even be able to add a v23.0 node to the config before it's even deployed, and nexus should smoothly switch to indexing it once it reached the right height. Untested.
- **Less special-cased e2e regression test exdcution path** across config, Go code, and scripts: e2e regression tests do not have node connectivity in …
=> Connect to oasis-node lazily

analyzer/queries/queries.go
Pretty bad testing fail :/ -- this has been released since v0.1.19.
Our e2e regressions did not catch this; I guess there was no suitable event in the range we're testing.
I'm building locally and will deploying as a hotfix on top of 0.1.20 to testnet prod and staging. (testnet prod is where this first led to a live error)
=> analyzer: Fix syntax error in SQL (TakeEscrow)

analyzer/block/block.go, analyzer/block/block_test.go, analyzer/queries/queries.go
This PR speeds up a query that runs on every startup. Tested on current staging testnet (~20M rows in table): The old query takes 77s, the new query takes ~32s. Still slow, but at least better.
The PR also adds a unit test for the query, and emits a log line before running the expensive query so that logs make more sense at nexus startup time when the program apparently freezes for a bit.
Resolves https://app.clickup.com/t/8692yjjtq
=> analyzer/block: more efficient db query on startup

coreapi/v22.2.11/staking/api/api.go, storage/oasis/nodeapi/api.go, storage/oasis/nodeapi/cobalt/node.go, storage/oasis/nodeapi/damask/node.go, storage/oasis/nodeapi/eden/convert.go, storage/oasis/nodeapi/eden/node.go, storage/oasis/nodeapi/history/history.go, tests/e2e/config/e2e-dev.yml
On the heels of https://github.com/oasisprotocol/docs/pull/600
This PR also renames `{Cobalt,Damask,Eden}ConsensusApiLite` to just `ConsensusApiLite`, letting the package names disambiguate between the various instances of `ConsensusApiLite`. That's less explicit but more idiomatic in Go and was requested/suggested by @ptrus recently.
Steps:
```
find -not -path '*/.git/*' -not -path './cache/*' -not -path '*/net-runner/*' -type f | xargs sed -i -E 's/enigma/eden/g'                                                
find -not -path '*/.git/*' -not -path './cache/*' -not -path '*/net-runner/*' -type f | xargs sed -i -E 's/Enigma/Eden/g'
git mv storage/oasis/nodeapi/{enigma,eden}
```
+ rename the ConsensusApiLite structs with IDE refactorings.
=> Rename enigma -> eden

cmd/bisect/data_fetch.go, cmd/bisect/main.go, storage/oasis/connections/raw_grpc.go, storage/oasis/nodeapi/api.go, storage/oasis/nodeapi/cobalt/node.go, storage/oasis/nodeapi/damask/node.go, storage/oasis/nodeapi/eden/node.go, storage/oasis/nodeapi/file/consensus.go, storage/oasis/nodeapi/history/history.go, storage/oasis/nodeapi/history/runtime.go, storage/oasis/nodeapi/universal_runtime.go
Debug tool in support of https://app.clickup.com/t/8692rq7ev (wherein the indexer dead-reckoned a negative number of escrow shares). But the tool is also intended for future debugging of any badly dead-reckoned values.
Sample output:
```
----------------------------------
GOOD height 3027601:   node 0                 db 0              
GOOD height 3885517:   node 0                 db 0              
GOOD height 4314476:   node 0                 db 0              
GOOD height 4528955:   node 0                 db 0              
GOOD height 4636195:   node 0                 db 0              
GOOD height 4663005:   node 0                 db 0              
GOOD height 4676410:   node 0                 db 0              
GOOD height 4683113:   node 0                 db 0              
GOOD …
```
=> Add "bisect" tool for finding where oasis-node and db diverge

analyzer/runtime/evm/client.go, analyzer/runtime/evm/client_test.go, analyzer/runtime/evm/erc721.go
a contract may arbitrarily lie to be detected as a certain token type and then emit events for a different kind of token. when these events cause analyzers to try to download information in a way that doesn't make sense, e.g. getting NFT information from an ERC-20 token, successfully complete the job with no data instead of aborting the download batch with an error.
this came up recently when a contract that didn't report itself as ERC-165 compatible and thus not ERC-721 compatible (as ERC-721 requires ERC-165 support) emitted ERC-721 Transfer events. the contract also implemented ERC721Enumerable, meaning it had a totalSupply() function, which is sufficient for us to recognize as an ERC-20 token.
=> runtime/evm: ignore unsupported token types

analyzer/runtime/evm/client.go, analyzer/runtime/extract.go, analyzer/runtime/extract_test.go, analyzer/runtime/visitors.go
https://app.clickup.com/t/8692tq704
```
oasisindexer=> select count(*) from chain.runtime_transactions where evm_encrypted_format='encrypted/x25519-deoxysii' and method='evm.Call' and success=true and evm_encrypted_result_data is not NULL;
count
-------
15318 <-- encrypted results
(1 row)
oasisindexer=> select count(*) from chain.runtime_transactions where evm_encrypted_format='encrypted/x25519-deoxysii' and method='evm.Call' and success=true and evm_encrypted_result_data is NULL;
count
--------
212680 <-- unencrypted results
```
Before:
```
indexer=# select runtime, round, tx_index, method, success, evm_encrypted_result_data from chain.runtime_transactions
;
runtime  |  round  | tx_index |  method  | success | evm_encrypted_result_data …
```
=> parse unencrypted results for confidential txs

analyzer/consensus/consensus.go, analyzer/queries/queries.go, analyzer/runtime/runtime.go, cmd/analyzer/analyzer.go, storage/migrations/02_runtimes.up.sql, storage/migrations/24_fast_sync_temp_tables.up.sql
Running the fast-sync analyzer with almost any parallelism (as low as parallelism=5) caused significant DB lock contention and consequently slowdowns.
This PR mostly removes the contention by replacing table UPDATEs with INSERTs into new temporary tables in a new `updates_todo` schema. Then after fast-sync, those temp tables get merged back into the "real" tables.
Testing: I locally modified the e2e_regression config to use fast-sync for the majority of the scanned range. Confirmed there were no diffs to the expected output.
Resolves https://app.clickup.com/t/8692uydfe
=> analyzer/fast-sync: Reduce DB contention by writing updates into a writeahead log

.golangci.yaml
This PR removes linters, as suggested by warnings that show up every time we run `golangci-lint`:
```
*** Running Go linters...
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused. 
```
=> lint: Remove obsolete linters

storage/client/client.go
we only set owner on transfers, so when we see e.g. Approval, we can add an NFT to the db without setting an owner (hm, but anyway). prevent the storage glue from breaking (attempts to scan NULL into owner address context identifier string) when viewing these entries
=> storage: handle NULL NFT owner

api/spec/v1.yaml
There were some places in the API specs that are generally applicable for all runtimes, but the documentation still referenced "Emerald". This changes replaces all those all references with the more appropriate "Runtime" word.
=> Removed hardwired "Emerald" from API docs

api/spec/v1.yaml
Follow-up to #581
The updated wording of the docs is more in sync with how we describe the other filters.
=> Improve documentation of the block hash argument

analyzer/evmabibackfill/evm_abi_backfill.go, analyzer/evmcontractcode/evm_contract_code.go, analyzer/queries/queries.go, cmd/analyzer/analyzer.go, config/config.go, storage/migrations/02_runtimes.up.sql, storage/migrations/26_runtime_abi.up.sql, tests/e2e_regression/e2e_config_2.yml
Part of https://app.clickup.com/t/866ad5hg1
Adds an analyzer to re-parse event body, tx data, and tx revert reason using known abis. 
Note: does not require a reindex
=> abi analyzer

analyzer/queries/queries.go, analyzer/runtime/extract.go, analyzer/runtime/runtime.go
previously I tried using COALESCE(new owner, old owner) so that we can pass nil to leave the owner as it is when we don't see any transfers, but that didn't leave a way to NULL out the owner when an NFT instance gets burned. the old code turned out to try to set a non-NULL empty string owner, which the Oasis address type doesn't allow.
this PR splits up the runtime analyzer's upsert into an upsert for any NFT detected, plus a new update for when we see transfers, which sets a new owner that may be NULL and bumps the num_transfers.
=> runtime: fix owner update for burned NFT instances

analyzer/queries/queries.go, analyzer/runtime/extract.go, analyzer/runtime/runtime.go
less use of special empty-string fake Address to signal weird conditions.
fields reordered too, so that the more important NumTransfers, which affects the validity of other fields, comes first
=> runtime: add explicit PossibleNFT.Burned field

analyzer/evmtokenbalances/evm_token_balances.go
it's checked above that balanceData is nil. this should have used the stale balance, as it's reporting that we didn't get a balance from the contract
=> evmtokenbalances: correct a log field

common/types.go, common/types_test.go
This PR adds custom (de)serialization for BigInt because it was broken.
The current version of our code CBOR-serializes every `BigInt` instance as `{}`, the empty struct (CBOR: `0xa0`). It was then deserialized as `0`.
BigInt is defined in our code as
```go
type BigInt struct {
big.Int
}
```
https://github.com/fxamacker/cbor/blob/master/encode.go explains that structs are serialized as maps. The inner `big.Int` is stored in an implicit `BigInt.Int` field, and is public (as evidenced by some sloppy usage in our own code). So IDK why it's not being serialized by cbor, and I'm fairly sure it was serialized correctly in the past.
Regardless, we did not have tests, which this PR also adds.
**Note:** Because the new serialization format is no longer map-based (if it ever was), my hope was that …
=> common/types: BigInt: CBOR-serialize correctly

analyzer/queries/queries.go
this query for enqueuing gaps seems to be crashing the database.
shall we revert to the slow and steady one?
=> Revert "analyzer/block: more efficient db query on startup"

analyzer/queries/queries.go, analyzer/runtime/runtime.go
in fast sync, a later call to the contract can get it marked as a contract candidate, and the bytecode analyzer may upsert it into the EVM contracts db before we get to analyzing its creation.
=> runtime: upsert evm contract creation info

storage/oasis/nodeapi/file/kvstore.go
it's nasty either way, but by not panicking here, we allow other kvstores to close gracefully
=> storage: avoid nil derference when closing uninitialized kvstore

analyzer/runtime/extract_test.go, analyzer/util/util_test.go, log/log_test.go, storage/postgres/client_test.go, storage/postgres/testutil/testutil.go, tests/e2e/e2e_test.go, tests/http/v1/governance_test.go, tests/http/v1/registry_test.go, tests/http/v1/staking_test.go, tests/http/v1/status_test.go, tests/http/v1/transactions_test.go, tests/statecheck/consensus_test.go, tests/statecheck/runtime_test.go, tests/statecheck/util.go
Use `{require,assert}.NoError` instead of `.Nil` in all test cases where error existence is checked. This makes the output more readable, which is especially useful in the statecheck tests:
```
consensus_test.go:168:
Error Trace:    /nexus/tests/statecheck/consensus_test.go:168
Error:          Expected nil, but got: &status.Error{s:(*status.Status)(0xc000307448)}
Test:           TestGenesisFull
```
vs
```
consensus_test.go:164:
Error Trace:    /nexus/tests/statecheck/consensus_test.go:164
Error:          Received unexpected error:
rpc error: code = Unimplemented desc = Only some methods are allowed on this proxy.
Test:           TestGenesisFull
```
=> tests: require.Nil -> require.NoError

api/spec/v1.yaml, storage/client/queries/queries.go, tests/e2e_regression/expected/emerald_txs.body
For non-evm transactions there are no fee refunds as there are for EVM transactions (where this is done to ensure EVM compatibility).
=> runtime-transactions: fix calculated `charged_fee` for non-evm txs

analyzer/block/block.go, analyzer/block/block_test.go, analyzer/consensus/consensus.go, analyzer/item/item.go, analyzer/node_stats/node_stats.go, analyzer/queries/queries.go, cmd/analyzer/analyzer.go, config/config.go, metrics/analysis.go
Resolves https://app.clickup.com/t/8692qbwf4
To enable the queuelength metric for runtime block analyzers, nexus needs the current chain heights of the runtimes. The `node_stats` analyzer currently fetches/stores this data only for consensus, so this PR also adds runtime support for the node_stats analyzer.
Note: We _could_ avoid this by fetching the chain heights directly in the block analyzers. Although the height would be fresher, it would also require a second round-trip in the main block processing loop. Since the metrics are internal-only I opted to use the chain heights we already store in `chain.latest_node_heights`. Open to suggestions though.
Alternatively alternatively, we could put the metric updating thing in a concurrent loop separate from the main block processing loop. Not …
=> [metrics] add block analyzer queuelength metrics

storage/migrations/05_util_fns.up.sql
The old migration files accidentally created the fns in the default schema, which is !=`public` in our deployment. Therefore, the `api` component wasn't able to call them, and the query at https://github.com/oasisprotocol/nexus/blob/fc099d75003d9b79ea20a040cd4cecf9e3168396/storage/client/queries/queries.go#L416-L416 crashed.
This PR fixes the issue for future runs that are starting with a wiped DB.
I manually moved the fns to `public` in mainnet and testnet staging, where they were in the wrong schema. Verified that in the new setup, the fn is accessible to analyzers _and_ the api.
=> db: Make eth_preimage() et al visible to api layer

analyzer/block/block.go
In slow sync, blocks arrive slowly, so the analyzer is almost always in the middle of processing a batch of blocks when the batchContext (5 minutes) times out. Every so often, the analyzer is also right in the middle of analyzing a block or writing it to the DB. When that happens, the block fails. This is harmless as the block is then retried, but looks ugly/alarming in the logs.
This PR makes the analyzer end the batch when the batchContext is merely _close to_ expiring.
=> analyzer/block: Preemptively terminate batch before timeout

analyzer/aggregate_stats/aggregate_stats.go, analyzer/aggregate_stats/queries.go, storage/migrations/00_consensus.up.sql
@lukaw3d reported that the latest transaction volume stats weren't up to date:
https://nexus.oasis.io/v1/emerald/blocks
```
"timestamp":"2024-01-19T17:30:48Z"
```
https://nexus.oasis.io/v1/emerald/stats/tx_volume?window_size_seconds=86400&window_step_seconds=86400&limit=30&offset=0
```
"window_end":"2023-11-26T00:00:00Z"
```
Upon closer inspection, the root cause was that the aggregate stats analyzer query to calculate `active_accounts` was taking a long time and blocking the calculation of other stats, including the transaction volume. This PR makes the queries more performant by 1) adding an index for consensus, and 2) rewriting the runtime active accounts query per @mitjat 's suggestion so that postgres now uses the existing index on the `runtime_related_transactions` table.
The index …
=> active_accounts query optimization

storage/client/queries/queries.go
there was another `bigint`, in that same line even :facepalm:
=> storage: correct nft id type again

api/spec/v1.yaml
Based on https://github.com/oasisprotocol/nexus/blob/dc95e6bcf9e75dee797c7bf17b91f67439ff940a/coreapi/v23.0/governance/api/proposal.go#L22-L25
=> api: enum proposal states

storage/migrations/03_statecheck_snapshots.up.sql, tests/statecheck/consensus_test.go, tests/statecheck/runtime_test.go, tests/statecheck/util.go
...and some other fixes:
- stale accounts (accounts queued to be required) are now skipped in the test, as those balances are expected to be out of date
- snapshot DB schema now includes the analyzer name, so that multiple statechecks can run concurrently (e.g. consensus, emerald and sapphire)
- handles accounts without any balances which can be missing in the address list returned from the oasis-node
- these are considered valid, if balance on nexus is also 0
=> statecheck: exempt accounts that are stale (to be requeried)

analyzer/runtime/evm/client_test.go, cmd/analyzer/analyzer.go, cmd/api/api.go, cmd/common/common.go, cmd/root.go, log/log.go, storage/oasis/nodeapi/cobalt/node.go, storage/oasis/nodeapi/damask/node.go, storage/oasis/nodeapi/eden/node.go, storage/oasis/nodeapi/file/consensus.go
This PR has two related small improvements to logging:
- We used NewDefaultLogger in a few places before; this is not great as the default logger does not reflect the .yml config (e.g. the desired logging level, the format, etc). We now use RootLogger (which is derived from the config) instead.
- `pogreb` was logging straight to `stderr`, so all its info-level logs were interpreted as errors by GCP, and stood out in the log browser. We now route pogreb logs through our JSON-formatted logger, at INFO level.
=> logging: Use global logging config everywhere

analyzer/aggregate_stats/queries.go
Resolves https://app.clickup.com/t/8693pa35b
Query changed as suggested by @pro-wh
=> optimize daily active accounts query

storage/postgres/client.go
pgx offers two ways of sending query batches to the DB: A faster one with poor error reporting, and a slower one with better errors.
Before this PR, we toggled between the two based on an env variable. This PR refactors the code (read the diff bottom to top) so that we always use the fast method, but if it fails, we retry with the slow method to obtain a better error msg. Since a failed tx is automatically reverted and since the retry is not async, there should be no harm in attempting the batch twice.
**Testing:** Deployed in staging mainnet. Sapphire block analyzer went from spending ~300ms per block on writing to ~40ms. :tada:
=> pgx: Transfer entire DB batch in one request

analyzer/consensus/genesis.go
These put pgx's pipeline out of sync when it expects to find an Exec result and instead finds the next query's output.
=> consensus: remove separator comment queries

common/types.go, storage/migrations/00_consensus.up.sql, storage/oasis/nodeapi/cobalt/convert.go
here's some changes we can extract from the roothash events line of work
new for nexus developers: common.StringOrNil(v) replaces:
```go
var vStringPointer *string
if (v != nil) {
vString := v.String()
vStringPointer = &vString
}
```
which comes up a lot in cases where we use *Address (or whatever) for optional fields going to the database
=> usable changes from roothash work

analyzer/uncategorized/addresses.go, api/spec/v1.yaml, api/v1/types/util.go
This PR removes YAML references in favor of openapi types and `$ref`-style references for all reusable types, notably `Address` and `BigInt`. It was prompted by https://github.com/oasisprotocol/explorer/issues/711
It also wraps all `$ref` references into `allOf`; this is a [workaround](https://github.com/OAI/OpenAPI-Specification/issues/1514#issuecomment-1386613645) (thank you @lukaw3d) for the fact `$ref` on its own [does not allow sibling attributes](https://swagger.io/docs/specification/using-ref/) like a custom description.
---
**OUTDATED** description follows, from before the workaround was known.
I'm on the fence whether to actually merge this PR:
- GOOD: Nexus still compiles with the new openapi, requiring no changes.
- BAD: When I compared the autogenerated Go code, I noticed all …
=> openapi: Use named types everywhere

api/spec/v1.yaml, tests/e2e_regression/expected/emerald_events.body
From https://github.com/oasisprotocol/nexus/pull/640#discussion_r1488734482
per @mitjat 's comment:
> I was surprised by all these explicit nulls, so I did some digging. These fields would be simply missing if they were tagged as json:"...,omitempty". The JSON tags are generated by oapi-codegen. And the reason that the tag does not get generated (it [normally does](https://github.com/deepmap/oapi-codegen/blob/v1.16.2/pkg/codegen/codegen_test.go#L126-L128)) is that the evm_log_name field is marked nullable in our openapi spec. Which, [per openapi](https://swagger.io/docs/specification/data-models/data-types/#null), means "this variable can contain an explicit null value".
> Looking at our openapi spec, we have 5 instances of nullable: true, and I don't think any of them are justified. What …
=> [api] remove nullable tags

.github/workflows/ci-test.yaml, .vacuum.yaml, api/spec/v1.yaml
Our existing OpenAPI validation CI action is [failing with HTTP 500](https://github.com/oasisprotocol/nexus/actions/runs/8009264534/job/21877527647?pr=633) when trying to download Chrome for Puppeteer.
It's a ridiculous enough dependency that it spurred this PR, which brings a substitute openapi validation tool, `vacuum`.
Unlike the old tool, the new one supports linting, and the PR fixes the few linting errors we had.
=> openapi: new linting tool, fix lint errors

common/types.go, tests/statecheck/consensus_test.go, tests/statecheck/runtime_test.go
Consensus statecheck was failing in part because it was unable to pull large (>uint64) balances from the db into internal uin64 variables:
```
Error:          Received unexpected error:
can't scan into dest[1]: cannot scan 70039999999999963480000000 into *uint64
```
**This PR:**
- fixes that bug in statecheck/consensus
- avoids some less critical unneccessary BigInt->uint64 conversions in statecheck/runtime
- tightens the test a little; we now do NOT ignore accounts with 0 balance but non-0 nonce
- (no-op: renames some cryptically-named variables)
**Testing:** Deployed a statecheck manually, verified in the output that type errors were gone.
=> statecheck: Use BigInt, not uint64, for balances

api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go, tests/e2e_regression/eden/expected/emerald_events.body
Part of https://app.clickup.com/t/8693up8ft
This PR updates the events query to augment the body of non-`evm.log` events with evm-style addresses when available. 
Todo:
- `evm.log` events always use evm-style addresses; is there a demand for returning the oasis-style address for those events as well? edit: not yet; will hold off here
Testing: Only manual and e2e_regression tests for now as this is an api-only change. Performance benchmarks on production showed that the new query is slower but still within acceptable bounds. 
Note: 
- The current impl does not scale well as the number of event body fields that can hold an oasis-style address increases, although I don't think it will increase much, if at all. An alternative impl would be to extract all oasis-style addresses from events and …
=> [api] return evm addresses in event body when available

storage/client/client.go, storage/client/queries/queries.go
Per https://github.com/oasisprotocol/nexus/pull/653#discussion_r1516723205, this PR shortens the query since the address context/identifier are checked later on anyway. If the check fails, the corresponding address field is nil as expected, so there is no change to api behavior.
=> [api] shorten query

analyzer/consensus/consensus.go, analyzer/queries/queries.go, api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go, storage/migrations/11_governance_votes.up.sql, tests/e2e_regression/damask/expected/votes.body, tests/e2e_regression/eden/expected/votes.body
Resolves https://app.clickup.com/t/8693prg5a
This PR adds two additional fields, `height` and `timestamp`, to the `ProposalVote` object in the api. 
As Mitja pointed out in the ticket, the "api fields will be optional because the votes might have been observed via the genesis doc rather than via events, in which case the voting height [is not available](https://github.com/oasisprotocol/nexus/blob/f6af89d1101fd6c983ade51755a44dee0b6d0597/analyzer/consensus/genesis.go#L571-L572)."
This is the case for the e2e_regression tests, which query for a proposal that was observed via genesis doc. 
Testing: e2e_regression tests, also I inserted some fake round data into the `votes` table and the resulting query looks like 
```
» curl "http://localhost:8008/v1/consensus/proposals/2/votes" | jq …
```
=> [consensus] add height/timestamp to governance votes

analyzer/evmabibackfill/evm_abi_backfill.go, analyzer/evmabibackfill/evm_abi_backfill_test.go, analyzer/runtime/abiparse/abiparse.go, analyzer/runtime/extract.go, analyzer/runtime/extract_test.go
Per discussion on slack, we want to return a more human-friendly default error message if no transaction revert reason is provided. 
Note:
* This PR only handles the case where the error message is `reverted: `. It does not handle the case where the error message is entirely empty, since this should never occur (staging mainnet has no instances of a failed tx with a rawErrMessage of `""`)
Testing:
* Unfortunately our e2e_regression test ranges don't include a suitable failed tx with an empty revert message. Tested manually on the [originally reported transaction](https://explorer.oasis.io/testnet/sapphire/tx/0x872d95e14bd497f35209539341958346a4e20ddf66d1ef2f282251294aa5d3d0):
```
~/oasis/oasis-block-indexer(andrew7234/default-runtime-tx-err*) » curl …
```
=> [analyzer] return default message if no revert reason specified

.changelog/.markdownlint.yml, .changelog/584.process.md, .changelog/README.md, .changelog/template.md.j2, .github/workflows/ci-lint.yaml, .github/workflows/release.yaml, .goreleaser.yaml, .markdownlint.yml, CHANGELOG.md, Makefile, common.mk, towncrier.toml
https://app.clickup.com/t/8692y7uuw
~Opening Draft PR, because I am not sure about requirements.~ During planning session we were talking about enforcing usage of Change Log fragments for now without other tools we usually combine with it (gitlint/punch etc).
Release process will require running `changelog` and `release-tag` with an optional version number.
=> Init Change Log fragments

.changelog/584.process.md, CHANGELOG.md
The diff was created with a combination of the `make changelog`, and autogenerated release notes from https://github.com/oasisprotocol/nexus/releases/new (which I regrouped and cleaned up a little).
All future similar PRs should only need `make changelog`.
=> Assemble changes for the 0.2.10 release

.changelog/660.internal.md, .github/workflows/ci-lint.yaml, .github/workflows/ci-test.yaml, .github/workflows/docker-nexus.yaml, .github/workflows/prepare-release.yaml
With the new release flow (#584), we cut every release by creating a special PR that assembles the changelog fragments.
This makes it so that that PR doesn't need to undergo full CI, allowing us to cut releases quickly if needed.
Testing: Ran CI with and without including `.github/**` in the ignore list.
=> Fast CI on "assemble release" PRs

.changelog/661.bugfix.md, analyzer/consensus/consensus.go, analyzer/consensus/consensus_test.go, analyzer/consensus/convert_tx.go, coreapi/v23.0/keymanager/api/secret.go
@mitjat reported that the testnet deployment was generating lots of error logs about being unable to cbor-decode the consensus tx body. Further investigation revealed that there was a change to the `roothash.ExecutorCommit.Commits.Header` struct between damask/eden that was not backwards-compatible but this change slipped through the cracks in #655 . 
The first commit of this PR fixes the known problem. The second commit adds adds all the types just in case. It's verbose but might be easier to maintain in the future.
Todo: test on production testnet [x] also production mainnet [x]
Todo: investigate why it didn't fail on the eden test range, which should have used the latest eden type of roothash.ExecutorCommit edit*: our eden test range doesn't have any of that type of tx
=> analyzer/consensus: enumerate all tx body types

.changelog/662.process.md, .github/workflows/ci-lint.yaml, Makefile
- prevent issues with dependabot PRs
- limit towncrier check to pull_request event to fix an issue with failing workflow for merge commits (push event)
- enable gitlint
=> Tweak ci-lint workflow

.changelog/665.internal.md, .github/workflows/ci-test.yaml, Makefile, tests/e2e_regression/accept.sh, tests/e2e_regression/common_test_cases.sh, tests/e2e_regression/damask/test_cases.sh, tests/e2e_regression/eden/test_cases.sh, tests/e2e_regression/ensure_consistent_config.sh, tests/e2e_regression/run.sh
- run.sh now runs the analysis too. no replacement for compare only, run the whole test instead
- there's no longer a separate "fill cache" target. no replacement, run the whole test instead
- there are no longer separate makefile targets for individual suites. instead run `tests/e2e_regression/run.sh <suite>`
- there are no longer separate makefile targets for accepting individual suites. run `tests/e2e_regression/accept.sh <suite>`
- each suite now has its own test_cases.sh. they source a shared common_test_cases.sh with the overlapping tests
- the symlink-dereferenced "expected" output copy is now scoped by suite name
- CI mistakenly git-diff'd against the non-symlink-dereferenced "expected" output. the code around here is restructured to prevent the two `git diff` invocations from …
=> tests: restructure e2e_regression

.changelog/679.bugfix.1.md, analyzer/queries/queries.go, analyzer/runtime/accounts.go, analyzer/runtime/runtime.go, api/spec/v1.yaml, scripts/git-hooks/pre-commit
pontusx is the first runtime where this makes a difference because it uses two separate SDK denominations. Before this PR, their stats got conflated in the total_received and total_sent metrics (i.e. the metric was a sum of the two SDK tokens, EUROe and TEST).
This PR is a no-op for other existing runtimes because the only SDK denomination they use is the native denomination.
=> analyzer/runtime: limit total_{received,sent} to native denomination

.changelog/681.internal.md, analyzer/evmverifier/evmverifier.go, analyzer/runtime/extract.go, analyzer/runtime/runtime.go, analyzer/util/addresses/addresses.go, analyzer/util/addresses/registration.go, analyzer/util/eth/eth.go
uncategorized/addresses.go stringify*() -> util/addresses/addresses.go From*()
uncategorized/addresses.go Extract() -> util/addresses/addresses.go SliceFromSet()
runtime/extract.go register* -> util/addresses/registration.go Register*()
uncategorized/eth.go -> util/eth/eth.go
previously we had some map[Address]bool address sets, this changes them to map[Address]struct{} which I thought we compromised on
=> analyzer: move some uncategorized code into new packages

.changelog/677.bugfix.1.md, analyzer/consensus/consensus.go, cmd/analyzer/analyzer.go, config/history.go
On Oasis mainnet, consensus block 8048955 does not exist: 8048954 is the last block of Cobalt, and 8048956 is the first block of Damask. This was an unintended side effect of the dump-restore Damask upgrade.
Nexus was unaware of this, and would get stuck on that block when reindexing the entire history. The only way to "unstick" it was (small) manual DB surgery. This PR hardcodes the block as an exception, and makes Nexus skip it.
**Testing:**
One-off manual test. Ran mainnet analysis with the following config:
```yaml
consensus:
from: 8_048_946  # Damask genesis was at 8_048_956; probe slightly into Cobalt
to:   8_048_966
```
and verified that blocks are analyzed as expected.
=> analyzer/consensus: Skip nonexistent mainnet block 8048955

.changelog/2663.internal.md, account-names/mainnet_consensus.json, account-names/mainnet_paratime.json, account-names/readme.txt, account-names/testnet_consensus.json, account-names/testnet_paratime.json
We have decided to temporarily store the metadata about known addresses in the nexus repo, so that the frontends can pull this directly from github.
Later, hopefully, Nexus will serve this data via some API.
See https://app.clickup.com/t/8693rg7nz for some details.
=> Add data about known addresses

.changelog/630.internal.md, analyzer/consensus/consensus.go, analyzer/consensus/genesis.go, analyzer/queries/queries.go
this kinda sucks
- db slower ~13s -> ~17s on eden genesis file
- can no longer print out queries into a migration-like file
also some of the ON CONFLICT is not exactly preserved, so might be some hidden bugs in network upgrades
measurements, very informal, only one run each
reuse
{"analyzer":"consensus","caller":"genesis.go:52","count":355437,"height":"genesis","level":"info","module":"analysis_service","msg":"generated genesis queries","ts":"2024-02-08T01:42:57.758442953Z"}
{"analyzer":"consensus","caller":"consensus.go:204","level":"info","module":"analysis_service","msg":"genesis document queries generated","process_duration":"32.732929903s","ts":"2024-02-08T01:42:57.758504654Z"}
{"analyzer":"consensus","caller":"consensus.go:228","level":"info","module":"analysis_service","msg":"genesi …
=> consensus: use batch for genesis queries

.changelog/692.bugfix.md, api/middleware.go, metrics/requests.go
Prometheus was filling up unusually fast. 
```
$ promtool tsdb analyze /prometheus
Label names with highest cumulative label value length:
1376859 exported_endpoint
47404 __name__
37378 id
34344 mountpoint
22659 name
Highest cardinality labels:
64210 exported_endpoint
1311 __name__
519 name
357 id
282 le
Highest cardinality metric names:
787440 api_request_latencies_bucket
65620 api_request_latencies_sum
65620 api_request_latencies_count
7620 nginx_ingress_controller_request_duration_seconds_bucket
7416 etcd_request_duration_seconds_bucket
```
That is 1.4GB per day just from the labels' text values on that one histogram metric (probably more for the table structure overhead).
So I queried `api_request_latencies_bucket` and found it was creating a new label for every unique request, …
=> metrics: avoid empty api_request_latencies_* entries

.changelog/693.bugfix.md, analyzer/node_stats/node_stats.go, cmd/analyzer/analyzer.go, storage/oasis/nodeapi/history/runtime.go
the node stats analyzer errored after redeploying on mainnet. This PR cleans up the analyzer and makes it more robust to unsupported runtimes.
=> node stats analyzer: handle nonexistent runtimes gracefully

.changelog/697.bugfix.md, storage/migrations/00_consensus.up.sql, storage/migrations/14_accounts_rel_tx_index.up.sql
@csillag reported that the `/consensus/transactions?rel={}` endpoint was very slow. Further investigation showed that the existing index did not contain enough information, which is fixed in this PR.
testing: Already enabled in testnet production; sample query is now performant: https://nexus.prd.oasis.io/v1/consensus/transactions?limit=10&offset=0&rel=oasis1qp65laz8zsa9a305wxeslpnkh9x4dv2h2qhjz0ec
=> augment ix_accounts_related_transactions_address_block index

.changelog/709.bugfix.md, storage/client/client.go, storage/client/queries/queries.go, tests/e2e_regression/damask/expected/epoch.body
The `/consensus/epochs/<latest_epoch>` endpoint for the currently active epoch returns the ever increasing 'end_height'.
This is inconsistent with the API spec and also with the `/consensus/epochs`. Skip returning the `end_height` for the latest epoch.
For `/consensus/epochs` we already do this.
=> api/epochs: Skip 'end_height' for latest epoch

.changelog/711.feature.md, analyzer/consensus/consensus.go, analyzer/queries/queries.go, storage/migrations/17_delegations_zero_shares.up.sql
This will ensure that the delegations with 0 shares get cleaned up/removed from the table.
=> delegations: remove delegations with 0 shares

.changelog/713.bugfix.md, analyzer/consensus/consensus.go
One more source of chain.delegations with `0` shares.
See relevant oasis-core code: https://github.com/oasisprotocol/oasis-core/blob/774316020d821c99307f444a4de21775fc01f048/go/consensus/cometbft/apps/staking/state/state.go#L996-L1001
=> delegations: do not track rewards as delegations

.changelog/701.bugfix.md, analyzer/aggregate_stats/aggregate_stats.go, analyzer/evmverifier/sourcify/client.go, analyzer/node_stats/node_stats.go, analyzer/runtime/runtime_test.go, api/middleware.go, api/spec/v1.yaml, api/v1/types/util.go, cmd/analyzer/analyzer.go, cmd/api/api.go, common/types.go, config/config.go, config/history.go, storage/client/client.go, storage/migrations/01_runtimes.up.sql, storage/migrations/19_pontusx_rename.up.sql
Previously, nexus would directly use the paratime name in the sdk-config, which is inconsistent with our internal `runtime` enum in the database. We are planning to [change the sdk-config](https://github.com/oasisprotocol/oasis-sdk/pull/1797), so this PR is intended as a patch until the upstream fix goes in.
Also contains several bugfixes for the pontusx api server. Already deployed in staging/production.
=> pontusx/pontusx_dev post-launch bugfixes

.changelog/719.bugfix.md, storage/client/client.go
Due to bugs, we can end up with invalid delegations in DB with 0 shares.
I believe most of these cases are fixed in: https://github.com/oasisprotocol/nexus/pull/713 https://github.com/oasisprotocol/nexus/pull/711 https://github.com/oasisprotocol/nexus/pull/712
but still, don't panic since this is part of the public API; instead, log an error and report 0 shares.
=> storage/client: don't crash on 0 delegated shares

.changelog/723.trivial.md, api/spec/v1.yaml
| Before | After |
| --- | --- |
| ![_home_luka_oasis_explorer_explorer-frontend_src_oasis-nexus_redoc-static html](https://github.com/oasisprotocol/nexus/assets/3758846/62853b03-3c99-4b6b-8224-0630315d6656) | ![_home_luka_oasis_explorer_explorer-frontend_src_oasis-nexus_redoc-static html (1)](https://github.com/oasisprotocol/nexus/assets/3758846/af8fa428-387d-44e2-ac5f-176ab7528a5d) |
=> Mark is_verified deprecated in API spec, not just in description

.changelog/731.trivial.md, api/spec/v1.yaml
| Before | After 689dae04fb48c1a4bb22b3e0fcfca61177563144 | After 35bda82e9df9d8eebd64603f7b8a94414232c400 |
| --- | --- | --- |
|  search looks less confusing | |
| ![nexus oasis io_v1_spec_v1 html](https://github.com/user-attachments/assets/a115aa63-5dfb-446a-af3d-1721209000ff) | ![_home_luka_Downloads_nexus_api_spec_v1 html](https://github.com/user-attachments/assets/74e8d5be-c97e-4cfa-9de4-f738ae698e75) | ![_home_luka_Downloads_nexus_api_spec_v1 html (1)](https://github.com/user-attachments/assets/272311b1-5908-49a8-980a-b4aa555c980e) |
| but start is more empty |   |
| ![nexus oasis io_v1_spec_v1 html (1)](https://github.com/user-attachments/assets/b346517b-dd3f-49a8-9147-ffb9d7e171f4) | ![_home_luka_Downloads_nexus_api_spec_v1 html …
=> API docs workaround to separate search panel in sidebar

.changelog/733.trivial.md, cmd/api/api.go, tests/e2e_regression/damask/expected/bad_account.headers, tests/e2e_regression/damask/expected/bad_node.headers, tests/e2e_regression/damask/expected/spec.headers, tests/e2e_regression/damask/expected/trailing_slash.headers, tests/e2e_regression/eden/expected/bad_account.headers, tests/e2e_regression/eden/expected/bad_node.headers, tests/e2e_regression/eden/expected/spec.headers, tests/e2e_regression/eden/expected/trailing_slash.headers
Addresses https://app.clickup.com/t/86954afaz
CORS headers were not returned for failing/malformed requests; this PR fixes that by manually running the CORS middleware.
```
» curl -i -H 'Origin: example.com' 'localhost:8008/v1/consensus/accounts/oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg1k'
HTTP/1.1 400 Bad Request
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Vary: Origin
X-Content-Type-Options: nosniff
Date: Wed, 31 Jul 2024 22:20:53 GMT
Content-Length: 227
{"msg":"Invalid format for parameter address: error unmarshalling 'oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg1k' text as *api.Address: address: decoding from bech32 failed: decoding bech32 failed: invalid separator index 43"}
```
@lukaw3d please lmk if this isn't sufficient; I tried testing on browser …
=> always enable cors middleware, even on failing requests

.changelog/738.feature.md, api/spec/v1.yaml, api/v1/strict_server.go, storage/client/client.go, storage/client/queries/queries.go, storage/client/types.go, tests/e2e_regression/damask/expected/validator.body, tests/e2e_regression/damask/expected/validators.body, tests/e2e_regression/eden/expected/validator.body, tests/e2e_regression/eden/expected/validators.body
Moves `voting_power_total` to a sibling struct (ValidatorsStats) in ValidatorList. Also adds the total number of delegators and the total staked amount in the network to the new ValidatorsStats.
The total number of delegators/staked amount is required for the dashboard view in the mocks.
=> api: add validator agg stats

.changelog/704.bugfix.md, storage/client/client.go
Unknown -> .Success = nil -> .Error = nil
Ok -> .Success = common.Ptr(true) -> .Error = nil
Failed -> .Success = common.Ptr(false) -> .Error not nil
is my understanding for today
fixes #704, unexpeced non-nil .Error
=> storage: nil out transaction .Error on unknown result

.changelog/748.feature.md, analyzer/runtime/runtime.go, storage/client/client.go
in fact the database allows NULL in these columns already, but a part of the analyzer fills in ""/0 
- allow inserting NULL
- no corrections to existing records
- rename variables to follow variable naming style
- no change to api.....................
=> runtime: store NULL error module/code when no error

.changelog/762.doc.md, api/spec/v1.yaml
=> openapi: mark unreleased consensus endpoints as experimental/deprecated

.changelog/760.feature.md, api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go, storage/client/types.go, tests/e2e_regression/damask/expected/validator.body, tests/e2e_regression/damask/expected/validator.headers, tests/e2e_regression/eden/expected/validator.body, tests/e2e_regression/eden/expected/validator.headers
https://app.clickup.com/t/8695px3eh
=> api/consensus/validators: Expose validator signed blocks info

.changelog/766.feature.md, cmd/api/api.go, config/config.go, config/docker-dev.yml, config/local-dev.yml, storage/client/client.go, storage/oasis/nodeapi/history/runtime.go, tests/e2e/config/e2e-dev.yml, tests/e2e_regression/damask/e2e_config_1.yml, tests/e2e_regression/damask/expected/emerald_contract_account.body, tests/e2e_regression/eden/e2e_config_1.yml, tests/e2e_regression/edenfast/e2e_config_1.yml
The server config had a (legacy?) `chain_name` field, which was only used in one place - to determine the runtime ID from the runtime name in the `API/runtime/status` endpoint. This was a bit of a kludge and didn't support custom networks.
The server config already contains the `SourceConfig` section, which supports both Default and Custom networks, so let's use that to determine the runtime ID.
Note needed change to configs is the following:
Old:
```yaml
server:
chain_name: mainnet
```
New:
```yaml
server:
source:
chain_name: mainnet
```
If the deployment already had the `server.source` configured, then just removing the existing `server.chain_name` is ok.
=> config/server: clean-up chainName and reuse source config

.changelog/797.bugfix.md, storage/oasis/nodeapi/history/history.go
Per report from @uscinski 
We've been deploying archive nodes on OPF side. So far we have Testnet gRPC 2022-03-03 and 2021-04-13. We tried to run Nexus analyzer that includes these both archive nodes. But Nexus crashes with the following error:
```
{"caller":"analyzer.go:130","error":"error creating consensus client: instantiating history consensus API lite: historical API for archive 2021-04-13 not implemented","level":"error","module":"nexus","msg":"service failed to start","ts":"2024-11-07T10:48:25.841983708Z"}
```
To me it looks like Nexus lacks implementation of the historical API and therefore cannot work with the said node. Is this correct or do we need to configure it differently (both Nexus and gRPC node)? We also tried to include only the 2022-03-03  archive node and so far …
=> add 2021 testnet to api constructors

.changelog/802.bugfix.md, storage/client/queries/queries.go
Reported by @buberdds in https://github.com/oasisprotocol/nexus/issues/794
The filter param needed to be updated.
=> api: filter rel accounts bugfix

.changelog/808.feature.md, storage/client/client.go, storage/migrations/01_runtimes.up.sql, storage/migrations/07_runtime_events_evm_contracts_events.up.sql, tests/e2e_regression/eden/expected/emerald_transfer_events_of_token.body, tests/e2e_regression/eden/expected/emerald_transfer_events_of_token.headers, tests/e2e_regression/eden/test_cases.sh
Part of: https://github.com/oasisprotocol/nexus/issues/804
This will enable efficient querying of all transfers of a specific ERC20 token. This is needed for the Transfer tab in the tokens details page (https://explorer.oasis.io/mainnet/sapphire/token/0x6665a6Cae3F52959f0f653E3D04270D54e6f13d8). See issue description for some more details.
Creating the index on the live instance might take some time, so ideally, the index is created CONCURENTLY sometime before deployment to prevent the migration from blocking the deployment.
Note: This doesn't resolve the inefficient accounts-related query, which is also mentioned in the issue. That one will require a separate (likely more significant) change.
TODO:
=> storage: add index for efficient fetching of events emitted by a specific contract

analyzer/aggregate_stats/aggregate_stats.go
Minifix extracted from: https://github.com/oasisprotocol/nexus/pull/809
=> analyer/aggregate_stats: fix errors check

.changelog/823.feature.md, api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go, tests/e2e_regression/damask/expected/events.body, tests/e2e_regression/eden/expected/events.body
Having events timestamps is useful; it also unifies the API with runtime events, which already contain timestamps.
TODO:
=> api/consensus/events: Include timestamp

.changelog/798.trivial.md, account-names/readme.txt, named-addresses/mainnet_consensus.json, named-addresses/mainnet_emerald.json, named-addresses/mainnet_sapphire.json, named-addresses/readme.txt, named-addresses/testnet_consensus.json, named-addresses/testnet_emerald.json, named-addresses/testnet_sapphire.json
In Explorer we want to show token names instead of contract addresses in multiple places
- moved hardcoded addresses to `named-accounts` 
- split paratime files into runtime specific
=> Add ERC721 and ERC20 to hardcoded named accounts

.changelog/821.feature.md, api/errors.go, cmd/api/api.go, config/config.go
Added `ContextTimeoutMiddleware` to enforce request context timeout and ensure proper cancellation of timed-out requests. This ensures that the context for requests exceeding the defined timeout limit are properly canceled.
I noticed cases like the one below, where request takes 15 seconds:
```json
{"caller":"middleware.go:77","latency":"14.69731168s","latency_bin":">1000ms","level":"info","module":"api","msg":"ending request","query_params":"limit=10&offset=0","query_path":"/v1/sapphire/evm_tokens","request_id":"3fecdf6b-ad74-42f0-8cfc-52ba0787f05a","status_code":200,"ts":"2024-12-05T08:37:32.086384228Z"}
```
Note that the server logs show a 200 OK status, but the response is not delivered to the client. Instead, the client receives an EOF since the [configured server timeout is …
=> server: cancel the request context on timeout

.changelog/832.feature.md, storage/migrations/10_util_fns_update.up.sql
Marking these functions as STABLE allows them to be used in index expressions and enables PostgreSQL to optimize queries by avoiding unnecessary recomputations of the function during query execution.
Without the STABLE attribute, PostgreSQL treats the functions as VOLATILE, forcing it to recompute the function every time it is called within a query, even if the input is static.
More details: https://www.postgresql.org/docs/current/xfunc-volatility.html#XFUNC-VOLATILITY
Changes already applied to nexus.prd and testnet.nexus.prd.
=> storage: Mark postgresql helpers functions as STABLE

.changelog/836.bugfix.md, storage/migrations/00_consensus.up.sql, storage/migrations/11_blocks_proposer_enitity_height_idx.up.sql
We always order by height, so make the index more efficient by including the height.
Already applied.
=> storage: Update block proposer index to include height

.changelog/837.feature.md, analyzer/item/item.go, analyzer/item/item_test.go, analyzer/validatorstakinghistory/validatorstakinghistory.go, config/config.go, tests/e2e_regression/damask/e2e_config_2.yml, tests/e2e_regression/eden/e2e_config_2.yml, tests/e2e_regression/edenfast/e2e_config_2.yml
This adds a configurable `MaxBackoffTime` to analyzers. This is useful for analyzers such as `validatorstakinghistory`, where once caught up, we only expect new work on epoch transitions and don't need to query every 6 seconds.
Additional note: the queries for fetching `validatorstakinghistory` work are not the most efficient (take ~2 seconds). I noticed this because these queries are currently using a lot of the database's CPUs—even if there's no work to be done. The idea is that with the `MaxBackoffTime` change, we don't need to bloat the DB with additional indexes and just be smarter about how frequently we do the queries.
Alternatives considered:
- We could manually update the deployment configuration for `validatorstakinghistory` to use a "fixed-interval" once caught up. But if the …
=> analyzer: configurable MaxBackoffTimeout

.changelog/838.feature.md, analyzer/queries/queries.go
Optimize `RuntimeEvmVerifiedContractEvents` query by switching DECODE to ENCODE for address comparison to leverage existing indexes on `chain.runtime_events`.
The query benefits a bit by partially using  `ix_runtime_events_evm_specific_contract_events`.
=> storage: optimize RuntimeEvmVerifiedContractEvents query

.github/workflows/docker-nexus.yaml, .github/workflows/release.yaml, analyzer/util/util.go
- Since we added configurable max backoff timeout, we should increase the internal upper bound as well: https://github.com/oasisprotocol/nexus/pull/837
- Fix release action permissions
=> Release followup updates

.changelog/849.bugfix.md, cmd/api/api.go
Fixes: https://github.com/oasisprotocol/nexus/issues/743
Placed`CorsMiddleware` outside of `TimeoutHandler` to ensure CORS headers are included in responses even when requests time out.
=> Return CORS headers also on timeout

.changelog/833.internal.md, go.mod, go.sum
Just a minor update: https://github.com/akrylysov/pogreb/releases/tag/v0.10.2
=> deps: update pogreb to v0.10.2

.changelog/885.feature.md, api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go, tests/e2e_regression/eden/expected/emerald_failed_tx.body, tests/e2e_regression/eden/expected/emerald_tx.body, tests/e2e_regression/eden/expected/emerald_txs.body, tests/e2e_regression/eden/expected/emerald_txs_by_method.body
Fixes https://github.com/oasisprotocol/nexus/issues/884
The existing sender_0, sender_0_eth, and nonce_0 are deprecated and will be removed in the future.
=> api/runtime/transactions: Add signers field to response

.changelog/898.doc.md, api/spec/v1.yaml
Now that we have released consensus support, we no longer have to mark these endpoints as Experimental / deprecated
=> openapi: remove experimental/deprecated markers from consensus endpoints

.changelog/913.bugfix.md, api/middleware.go, cmd/api/api.go, cmd/api/api_test.go
Fixes: https://github.com/oasisprotocol/nexus/issues/912
- Metrics Middleware: Now validates metric names for valid UTF-8 to prevent Prometheus panics. 
- Safe File Serving: Introduced a safeFileSystem wrapper that only serves regular files, rejecting symlinks and directories, and added some additional path validation.
- Added tests covering various edge cases, including invalid UTF-8, null byte injection, and attempts to access restricted paths.
=> api: harden file server security

.changelog/919.bugfix.md, storage/client/client.go
=> api/transactions: Limit number of methods provided in the filter

.changelog/922.bugfix.md, analyzer/runtime/decode_events.go
The Nexus Sapphire Testnet analyzer got stuck at processing block `10653792` that includes the new recently added `InstanceRegisteredEvent` (https://github.com/oasisprotocol/oasis-sdk/pull/2159). This PR adds support for decoding such events that was missing in https://github.com/oasisprotocol/nexus/pull/917. 
```
{"analyzer":"sapphire","caller":"block.go:412","height":10653792,"level":"info","mode":"slow-sync","module":"analysis_service","msg":"processing block","ts":"2025-03-05T18:00:43.160965827Z"}
{"analyzer":"sapphire","caller":"block.go:425","err":"extract non-tx events: event 6: decode rofl: invalid rofl event code: 4; raw event: {Module:rofl Code:4 Value:[129 162 99 114 97 107 161 103 101 100 50 53 53 49 57 88 32 22 23 122 67 18 40 176 86 9 150 65 237 63 79 58 186 10 247 12 51 163 …
```
=> rofl: Fix support for Instance Registered event

.changelog/923.trivial.md, api/spec/v1.yaml
Related to https://github.com/oasisprotocol/nexus/pull/820
=> openapi: Document missing `success` field in two-step transactions

.changelog/925.trivial.md, named-addresses/testnet_pontusxdev.json, named-addresses/testnet_pontusxtest.json
testnet pontusxdev and pontusxtest are both similar to sapphire. For now, the same names addresses are also valid there.
This commit adds the corresponding JSON lists.
(Which are simply copies for the one for Sapphire.)
=> Add named addresses for pontusxdev and pontusxtest runtimes

.changelog/929.feature.md, cmd/bisect/main.go, cmd/common/common.go, config/config.go, storage/postgres/client.go, storage/postgres/client_test.go, storage/postgres/testutil/testutil.go, tests/statecheck/util.go
By default `pgxpool` uses a very conservative limit for maximum number of connections (`max(num_cpu's, 4)`). We make this configurable, and also bump the default to 10.
In production we probably want to bump this to something like 50 or 100.
=> storage/db: Configuring max connection to the database

.changelog/933.feature.md, config/config.go
Fixes: https://github.com/oasisprotocol/nexus/issues/932
This should be good enough since we only use env variables for a couple of config settings (none of those should have commas unless providing a list of values).
=> config: add support for array values via environment variables

.changelog/912.bugfix.md, cmd/bisect/main.go, cmd/common/common.go, config/config.go, storage/postgres/client.go, storage/postgres/client_test.go, storage/postgres/testutil/testutil.go, tests/statecheck/util.go
As mentioned in https://github.com/oasisprotocol/nexus/pull/929/files#r2009079229
No need to provide a config option for this, as it can be specified in the db connection string.
=> storage/db: Remove max connection configuration option

.changelog/945.internal.md, .github/workflows/ci-lint.yaml, .github/workflows/ci-test.yaml, .github/workflows/docker-nexus.yaml, .github/workflows/prepare-release.yaml, .github/workflows/release.yaml
Ubuntu 20-04 images are getting deprecated: https://github.com/actions/runner-images/issues/11101
=> internal: bump CI to ubuntu-22.04

.changelog/963.bugfix.1.md, .changelog/963.bugfix.2.md, analyzer/runtime/accounts.go, analyzer/runtime/extract.go, storage/migrations/22_runtime_transactions_status_fix.up.sql
Fixes: https://github.com/oasisprotocol/nexus/issues/963
Also do not override the success field for failed transactions.
TODO:
=> analyzer/runtime: Fix 'success' compute for undelegate tx

.changelog/967.feature.md, storage/client/client.go, storage/client/queries/queries.go, tests/e2e_regression/common_test_cases.sh, tests/e2e_regression/damask/expected/txs_by_related_account.body, tests/e2e_regression/damask/expected/txs_by_related_account.headers, tests/e2e_regression/damask/expected/txs_by_related_account_and_method.body, tests/e2e_regression/damask/expected/txs_by_related_account_and_method.headers, tests/e2e_regression/damask/expected/txs_by_sender_and_method.body, tests/e2e_regression/damask/expected/txs_by_sender_and_method.headers, tests/e2e_regression/eden/expected/txs_by_related_account.body, tests/e2e_regression/eden/expected/txs_by_related_account.headers, tests/e2e_regression/eden/expected/txs_by_related_account_and_method.body, tests/e2e_regression/eden/expected/txs_by_related_account_and_method.headers, tests/e2e_regression/eden/expected/txs_by_sender_and_method.body, tests/e2e_regression/eden/expected/txs_by_sender_and_method.headers
Fixes #966
Split Transactions query based on the presence of related address filter.
=> api/transactions: Optimize related accounts filtering

.changelog/982.feature.md, api/spec/v1.yaml, api/v1/strict_server.go, storage/client/client.go, storage/client/queries/queries.go, tests/e2e_regression/eden_testnet_2025/expected/sapphire_rofl_app_instance.body, tests/e2e_regression/eden_testnet_2025/expected/sapphire_rofl_app_instance.headers, tests/e2e_regression/eden_testnet_2025/test_cases.sh
This endpoint was missed in the initial rofl API implementation.
=> api/rofl: Add endpoint for fetching a specific rofl app instance

.changelog/998.bugfix.md, analyzer/queries/queries.go, analyzer/rofl/instance_transactions/instance_transactions.go, analyzer/runtime/runtime.go, api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go, storage/migrations/01_runtimes.up.sql, storage/migrations/19_runtime_rofl.up.sql, storage/migrations/26_runtime_rofl_metadata_name.up.sql, storage/migrations/27_runtime_rofl_num_transactions.up.sql
Fixes: https://github.com/oasisprotocol/nexus/issues/989
Some fixes/optimisation for the rofl apps query:
- num_transactions is kept in DB, avoiding the need to compute the number of all rofl related transactions on the fly (this was getting huge, since we had to count all transactions ever submitted by all rofl instances for each rofl app)
- separate query to fetch first/last activity txs for ROFL apps, that way we only fetch these for the selected matched ROFL apps (e.g. 10 or 100) and not all ROFL apps
TODO:
=> api/rofl_apps: Optimize rofl apps query

.changelog/466.feature.md, storage/migrations/01_runtimes.up.sql, storage/migrations/30_evm_tokens_name_index.up.sql
from #460 
This speeds up searching tokens by name. For simplicity, we're not merging this for now (2024-06) until search proves problematically slow.
=>  storage: add chain.evm_tokens token_name index

.changelog/935.bugfix.md, analyzer/queries/queries.go, storage/migrations/01_runtimes.up.sql, storage/migrations/34_runtime_abi_parsed_at.up.sql
Fixes #910 
- add indexes for efficient evmabi-backfill analyzer queries, and update the queries for efficient index usage
- make `abi_parsed_at` field in runtime_transactions and events non-nill, to simplify queries and improve index usage
TODO:
- almost instant, and using the indexes as expected 
```
RuntimeEvmVerifiedContractTxs
QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=698040.63..698043.13 rows=1000 width=880) (actual time=134.601..134.607 rows=7 loops=1)
->  Sort  (cost=698040.63..698465.63 rows=170000 width=880) (actual time=134.600..134.604 rows=7 loops=1)
Sort Key: tx.round DESC
Sort Method: …
```
=> evmabi-backfill: Optimize db queries

.changelog/1032.feature.md, storage/migrations/00_consensus.up.sql, storage/migrations/35_history_validators_epoch_idx.up.sql
This makes the query `ValidatorStakingHistoryUnprocessedEpochs`  used by validator_history analyzer efficient.
The table and the index are small compared to other tables, so overhead by adding this index is small.
=> Add epoch index for history.validators

go.mod, go.sum
Includes: https://github.com/oasisprotocol/oasis-sdk/pull/2230
After the fix is confirmed, tag a new oasis-sdk version and update to that.
=> Update oasis-sdk to include rofl tx fix

.changelog/1068.feature.md, analyzer/block/block.go, analyzer/consensus/consensus.go, analyzer/consensus/data_fetch.go, analyzer/runtime/runtime.go
In the old code, when the block analyzer was near the head of the chain, the backoff was almost always at 6 seconds. 
See retry interval quickly increasing to 6 seconds on a recently started node that is at the head of the chain:
```json
{"analyzer":"sapphire","caller":"block.go:420","height":12287791,"level":"info","mode":"slow-sync","module":"analysis_service","msg":"no data available; will retry","retry_interval_ms":100,"ts":"2025-06-25T08:36:03.901279912Z"}
{"analyzer":"sapphire","caller":"block.go:420","height":12287791,"level":"info","mode":"slow-sync","module":"analysis_service","msg":"no data available; will retry","retry_interval_ms":200,"ts":"2025-06-25T08:36:04.13376454Z"}
{"analyzer":"sapphire","caller":"block.go:420","height":12287791,"level":"info","mode":"slow-sync","module" …
```
=> analyer/block: Simplify and improve batch processing

.changelog/1071.feature.md, analyzer/queries/queries.go, analyzer/rofl/rofl.go, api/spec/v1.yaml, storage/client/client.go, storage/client/queries/queries.go, storage/migrations/19_runtime_rofl.up.sql, storage/migrations/42_runtime_rofl_instances_metadata.up.sql
Initially, rofl apps did not have metadata. Update rofl instances to support metadata and queue refresh of all active rofl apps, so that the instance metadata is fetched.
=> rofl_instances: Support rofl instance metadata

.changelog/1073.bugfix.md, analyzer/consensus/consensus.go, analyzer/runtime/runtime.go
This makes it consistent with other (runtime) block analyzers.
=> analyzer/consensus: Record timing only for successful requests

.changelog/1102.feature.md, .github/workflows/ci-test.yaml, .golangci.yaml, Makefile, analyzer/neby_prices/neby_prices.go, analyzer/neby_prices/queries.go, analyzer/pubclient/pub_client.go, api/spec/v1.yaml, cmd/analyzer/analyzer.go, common/types.go, common/types_test.go, config/config.go, go.mod, go.sum, storage/client/client.go, storage/client/queries/queries.go, storage/migrations/01_runtimes.up.sql, storage/migrations/44_runtime_evm_tokens_neby.up.sql, tests/e2e_regression/eden_2025/e2e_config_2.yml, tests/e2e_regression/eden_2025/expected/sapphire_token_by_name.body, tests/e2e_regression/eden_2025/expected/sapphire_token_configured_addresses.body, tests/e2e_regression/eden_2025/expected/sapphire_tokens.body, tests/e2e_regression/eden_2025/expected/sapphire_tokens_sort_market_cap.body
Fixes: https://github.com/oasisprotocol/nexus/issues/953
Add support for fetching EVM token prices from Neby subgraph
- Introduces `neby_derived_price` to the database and API, sourced directly from the Neby DEX GraphQL API.
- Unlike Uniswap v2, we do not parse on-chain events or follow swaps; instead, we rely on the subgraph’s `derivedETH` field as the canonical price. This significantly simplifies the implementation and is acceptable given that the price is primarily used for token sorting.
- The analyzer is currently hardcoded to Neby; the implementation can be generalized in the future to support additional sources or DEX subgraphs if needed.
=> runtime/evm_tokens: Fetch Neby price for tokens

.changelog/1107.internal.md, .golangci.yaml, go.mod, go.sum, storage/client/client.go
Fixes #887
The API currently uses an in-memory cache for a specific endpoint(consensus block), while no caching is applied to other cases. This somewhat arbitrary choice stems from historical decisions without clear justification. In practice, the utilization of this cache is very low, so we remove the cache for now.
=> storage/client: Remove consensus block cache
